<?php
$styles = sc_get_block_styles();
$style = $styles['css'] ?? '';
$class = $styles['classnames'] ?? '';

// TODO: Will be replaced once checkout script is added.
$checkoutJson = '{
    "id": "aa710cfd-f5a9-4918-aa03-8471a3b13808",
    "object": "checkout",
    "abandoned_checkout_enabled": true,
    "abandoned_checkout_return_url": "http:\/\/clientlinktest.local\/surecart\/redirect",
    "amount_due": 100000,
    "applied_balance_amount": 0,
    "billing_matches_shipping": true,
    "credited_balance_amount": 0,
    "currency": "usd",
    "discount_amount": 0,
    "email": "ctschaeffer@gmail.com",
    "first_name": "Maniruzzaman",
    "free_shipping_choice_shortage_amount": null,
    "full_amount": 100000,
    "group_key": null,
    "ip_address": "::1",
    "last_name": "Akash",
    "live_mode": false,
    "manual_payment": false,
    "metadata": {
        "page_id": "10249",
        "page_url": "http:\/\/clientlinktest.local\/shop\/",
        "wp_created_by": "1"
    },
    "name": "Maniruzzaman Akash",
    "net_paid_amount": 0,
    "paid_amount": 0,
    "paid_at": null,
    "payment_method_required": true,
    "phone": null,
    "proration_amount": 0,
    "refunded_amount": 0,
    "remaining_amount_due": 100000,
    "reusable_payment_method_required": true,
    "selected_shipping_choice_required": false,
    "shipping_address_accuracy_requirement": "tax",
    "shipping_amount": 0,
    "shipping_enabled": false,
    "shipping_tax_amount": 0,
    "shipping_tax_rate": 0,
    "status": "draft",
    "subtotal_amount": 100000,
    "tax_amount": 0,
    "tax_behavior": "exclusive",
    "tax_breakdown": [],
    "tax_enabled": true,
    "tax_label": null,
    "tax_status": "address_invalid",
    "total_amount": 100000,
    "total_savings_amount": 0,
    "trial_amount": 0,
    "upsells_expire_at": null,
    "billing_address": null,
    "current_payment_intent": null,
    "last_click": null,
    "customer": {
        "id": "3298e10d-41f9-41a6-a65d-df21a5ca5629",
        "object": "customer",
        "affiliation_expires_at": null,
        "billing_matches_shipping": true,
        "email": "ctschaeffer@gmail.com",
        "first_name": "Maniruzzaman",
        "indexed": true,
        "last_name": "Akash",
        "live_mode": false,
        "name": "Maniruzzaman Akash",
        "phone": null,
        "unsubscribed": false,
        "tax_enabled": true,
        "affiliation": null,
        "billing_address": null,
        "default_payment_method": null,
        "shipping_address": {
            "id": "363b6add-d7ef-4f7b-a6f2-7d4f490b99d3",
            "object": "address",
            "city": "JSDHJ",
            "country": "NL",
            "line_1": "ND",
            "line_2": null,
            "name": null,
            "postal_code": "12121",
            "state": null,
            "created_at": 1712585485,
            "updated_at": 1712585485
        },
        "tax_identifier": "674e8b1f-c827-48bd-bb36-c7306116b9e8",
        "created_at": 1712118390,
        "updated_at": 1712585485
    },
    "line_items": {
        "object": "list",
        "pagination": {
            "count": 1,
            "limit": 50,
            "page": 1,
            "url": "\/v1\/line_items?checkout_ids%5B%5D=aa710cfd-f5a9-4918-aa03-8471a3b13808"
        },
        "data": [
            {
                "id": "f0bf6888-073b-4716-a65c-a822c35ef700",
                "object": "line_item",
                "ad_hoc_amount": null,
                "discount_amount": 0,
                "fees_amount": 0,
                "full_amount": 100000,
                "fulfilled_quantity": 0,
                "purchasable_status": "purchasable",
                "quantity": 5,
                "scratch_amount": 100000,
                "stock_held": false,
                "subtotal_amount": 100000,
                "tax_amount": 0,
                "tax_rate": 0,
                "total_amount": 100000,
                "total_savings_amount": 0,
                "trial": false,
                "trial_amount": 0,
                "variant_options": null,
                "bump": null,
                "checkout": "aa710cfd-f5a9-4918-aa03-8471a3b13808",
                "fees": {
                    "object": "list",
                    "pagination": {
                        "count": 0,
                        "limit": 20,
                        "page": 1,
                        "url": "\/v1\/fees?line_item_ids%5B%5D=f0bf6888-073b-4716-a65c-a822c35ef700"
                    },
                    "data": []
                },
                "price": {
                    "id": "e61a992e-791a-4bc1-8858-0fc63ed5cdf3",
                    "object": "price",
                    "ad_hoc": false,
                    "ad_hoc_max_amount": null,
                    "ad_hoc_min_amount": 0,
                    "amount": 20000,
                    "archived": false,
                    "archived_at": null,
                    "currency": "usd",
                    "current_version": true,
                    "full_amount": 20000,
                    "license_activation_limit": null,
                    "metadata": {
                        "wp_created_by": "1"
                    },
                    "name": null,
                    "position": 0,
                    "portal_subscription_update_enabled": true,
                    "revoke_after_days": null,
                    "recurring_interval": null,
                    "recurring_interval_count": null,
                    "recurring_period_count": null,
                    "recurring_end_behavior": null,
                    "scratch_amount": null,
                    "setup_fee_amount": 0,
                    "setup_fee_enabled": false,
                    "setup_fee_trial_enabled": true,
                    "setup_fee_name": null,
                    "trial_duration_days": null,
                    "product": {
                        "id": "9217cd9e-6545-4def-b00f-b37accd72073",
                        "object": "product",
                        "allow_out_of_stock_purchases": false,
                        "archived": false,
                        "archived_at": null,
                        "auto_fulfill_enabled": true,
                        "available_stock": -6,
                        "description": null,
                        "held_stock": 6,
                        "featured": true,
                        "licensing_enabled": false,
                        "license_activation_limit": null,
                        "metadata": {
                            "wp_created_by": "1",
                            "wp_template_id": "pages\/template-surecart-product.php",
                            "wp_buy_link_enabled": "true",
                            "wp_buy_link_test_mode_enabled": "true"
                        },
                        "purchase_limit": null,
                        "metrics": {
                            "currency": "usd",
                            "max_price_amount": 20000,
                            "min_price_amount": 20000,
                            "prices_count": 1
                        },
                        "name": "Simple product - New",
                        "recurring": false,
                        "shipping_enabled": false,
                        "sku": null,
                        "slug": "simple-product-1",
                        "status": "published",
                        "stock": 0,
                        "stock_enabled": false,
                        "tax_enabled": true,
                        "tax_category": "tangible",
                        "weight": 0,
                        "weight_unit": "lb",
                        "commission_structure": null,
                        "featured_product_media": {
                            "id": "cbd7481b-63ce-465c-93d3-d57a75b609b2",
                            "object": "product_media",
                            "alt": null,
                            "position": 0,
                            "title": null,
                            "url": null,
                            "media": {
                                "id": "74870bc4-d561-43d6-aec0-2c1cec859168",
                                "object": "media",
                                "alt": null,
                                "byte_size": 145873,
                                "content_type": "image\/jpeg",
                                "extension": "jpeg",
                                "filename": "mens-shirt-white.jpeg",
                                "height": 1200,
                                "public_access": true,
                                "release_json": null,
                                "title": null,
                                "url": "https:\/\/media.surecart.com\/ili11628cn2zzuu7rj9zcfumzsbc",
                                "width": 1200,
                                "url_expires_at": null,
                                "created_at": 1691389056,
                                "updated_at": 1691389056
                            },
                            "product": "9217cd9e-6545-4def-b00f-b37accd72073",
                            "created_at": 1701257482,
                            "updated_at": 1701257482
                        },
                        "product_group": null,
                        "current_release_download": null,
                        "shipping_profile": "88cb950c-5ff1-48ed-9cc1-390b92016d07",
                        "discarded_at": null,
                        "product_collections": {
                            "object": "list",
                            "pagination": {
                                "count": 0,
                                "limit": 20,
                                "page": 1,
                                "url": "\/v1\/product_collections?product_ids%5B%5D=9217cd9e-6545-4def-b00f-b37accd72073"
                            },
                            "data": []
                        },
                        "variants": {
                            "object": "list",
                            "pagination": {
                                "count": 0,
                                "limit": 250,
                                "page": 1,
                                "url": "\/v1\/variants?product_ids%5B%5D=9217cd9e-6545-4def-b00f-b37accd72073"
                            },
                            "data": []
                        },
                        "image_url": "https:\/\/media.surecart.com\/ili11628cn2zzuu7rj9zcfumzsbc",
                        "created_at": 1699625079,
                        "updated_at": 1701262543,
                        "image_srcset": "https:\/\/surecart.com\/cdn-cgi\/image\/fit=scale-down,format=auto,width=320\/https:\/\/media.surecart.com\/ili11628cn2zzuu7rj9zcfumzsbc 320w, https:\/\/surecart.com\/cdn-cgi\/image\/fit=scale-down,format=auto,width=640\/https:\/\/media.surecart.com\/ili11628cn2zzuu7rj9zcfumzsbc 640w, https:\/\/surecart.com\/cdn-cgi\/image\/fit=scale-down,format=auto,width=960\/https:\/\/media.surecart.com\/ili11628cn2zzuu7rj9zcfumzsbc 960w, https:\/\/surecart.com\/cdn-cgi\/image\/fit=scale-down,format=auto,width=1280\/https:\/\/media.surecart.com\/ili11628cn2zzuu7rj9zcfumzsbc 1280w, https:\/\/surecart.com\/cdn-cgi\/image\/fit=scale-down,format=auto,width=1920\/https:\/\/media.surecart.com\/ili11628cn2zzuu7rj9zcfumzsbc 1920w",
                        "checkout_permalink": "http:\/\/clientlinktest.local\/buy\/simple-product-1",
                        "permalink": "http:\/\/clientlinktest.local\/products\/simple-product-1",
                        "page_title": "Simple product - New",
                        "meta_description": "",
                        "active_prices": [],
                        "featured_media": {
                            "alt": "Simple product - New",
                            "title": "",
                            "url": "https:\/\/media.surecart.com\/ili11628cn2zzuu7rj9zcfumzsbc"
                        },
                        "template_id": "pages\/template-surecart-product.php",
                        "first_variant_with_stock": null,
                        "initial_price": null,
                        "initial_amount": null,
                        "scratch_amount": null,
                        "template": null,
                        "template_part_id": "surecart\/surecart\/\/product-info",
                        "template_part": {
                            "type": "wp_template_part",
                            "theme": "surecart\/surecart",
                            "slug": "product-info",
                            "id": "surecart\/surecart\/\/product-info",
                            "title": "Products",
                            "content": "<!-- wp:surecart\/columns -->\n<div class=\"wp-block-surecart-columns\">\n\t<!-- wp:surecart\/column {\"layout\":{\"type\":\"constrained\",\"justifyContent\":\"center\",\"contentSize\":\"100%\"},\"width\":\"64%\"} -->\n\t<div class=\"wp-block-surecart-column is-layout-constrained is-horizontally-aligned-center\"\n\t\tstyle=\"flex-basis:64%;--sc-column-content-width:100%\"><!-- wp:surecart\/product-media \/--><\/div>\n\t<!-- \/wp:surecart\/column -->\n\n\t<!-- wp:surecart\/column {\"width\":\"36%\",\"style\":{\"spacing\":{\"blockGap\":\"24px\"}}} -->\n\t<div class=\"wp-block-surecart-column\" style=\"flex-basis:36%;--sc-form-row-spacing:24px\">\n\t\t<!-- wp:surecart\/product-collection-badges {\"count\":\"1\",\"style\":{\"typography\":{\"fontSize\":\"14px\"}}} \/-->\n\n\t\t<!-- wp:surecart\/product-title {\"style\":{\"typography\":{\"fontSize\":\"30px\",\"fontStyle\":\"normal\",\"fontWeight\":\"600\",\"letterSpacing\":\"0px\"},\"spacing\":{\"margin\":{\"top\":\"0\"}}}} \/-->\n\n\t\t<!-- wp:surecart\/product-price {\"style\":{\"typography\":{\"fontSize\":\"24px\"}}} \/-->\n\n\t\t<!-- wp:surecart\/product-description {\"style\":{\"typography\":{\"fontSize\":\"16px\"}}} \/-->\n\n\t\t<!-- wp:surecart\/product-variant-choices {\"style\":{\"typography\":{\"fontSize\":\"16px\"}}} \/-->\n\n\t\t<!-- wp:surecart\/product-price-choices {\"style\":{\"typography\":{\"fontSize\":\"16px\"}}} \/-->\n\n\t\t<!-- wp:surecart\/product-quantity {\"label\":\"Quantity\",\"style\":{\"typography\":{\"fontSize\":\"16px\"}}} \/-->\n\n\t\t<!-- wp:surecart\/product-buy-buttons -->\n\t\t<div class=\"wp-block-surecart-product-buy-buttons wp-block-buttons sc-block-buttons is-layout-flex\">\n\t\t\t<!-- wp:surecart\/product-buy-button {\"add_to_cart\":true,\"text\":\"Add To Cart\",\"width\":100,\"className\":\"is-style-fill\"} \/-->\n\n\t\t\t<!-- wp:surecart\/product-buy-button {\"text\":\"Buy Now\",\"width\":100,\"className\":\"is-style-outline\"} \/-->\n\t\t<\/div>\n\t\t<!-- \/wp:surecart\/product-buy-buttons -->\n\t<\/div>\n\t<!-- \/wp:surecart\/column -->\n<\/div>\n<!-- \/wp:surecart\/columns -->",
                            "description": "Display all individual products content unless a custom template has been applied.",
                            "source": "plugin",
                            "origin": "plugin",
                            "wp_id": null,
                            "status": "publish",
                            "has_theme_file": true,
                            "is_custom": false,
                            "author": null,
                            "post_types": [
                                "sc_product",
                                "sc_collection",
                                "sc_bump"
                            ],
                            "area": "uncategorized",
                            "modified": null
                        },
                        "display_amount": "",
                        "is_on_sale": false
                    },
                    "discarded_at": null,
                    "created_at": 1701257516,
                    "updated_at": 1701262543,
                    "display_amount": "$200",
                    "scratch_display_amount": "",
                    "is_on_sale": false,
                    "trial_text": null,
                    "setup_fee_text": "",
                    "payments_text": "0 payments",
                    "interval_text": "",
                    "short_interval_text": "",
                    "is_zero_decimal": false,
                    "currency_symbol": "$"
                },
                "upsell": null,
                "bump_amount": null,
                "created_at": 1714044037,
                "updated_at": 1715675813,
                "currency": "usd",
                "display_adhoc_amount": "",
                "display_bump_amount": "",
                "display_scratch_amount": "$1,000",
                "display_tax_amount": "",
                "display_subtotal_amount": "$1,000",
                "display_total_amount": "$1,000",
                "display_full_amount": "$1,000",
                "display_trial_amount": "",
                "price_id": "e61a992e-791a-4bc1-8858-0fc63ed5cdf3",
                "checkout_id": "aa710cfd-f5a9-4918-aa03-8471a3b13808"
            }
        ]
    },
    "manual_payment_method": null,
    "order": null,
    "recommended_bumps": {
        "object": "list",
        "pagination": {
            "count": 0,
            "limit": 10,
            "page": 1,
            "url": "\/v1\/bumps?checkout_ids%5B%5D=aa710cfd-f5a9-4918-aa03-8471a3b13808"
        },
        "data": []
    },
    "referral": null,
    "shipping_address": [],
    "tax_identifier": null,
    "selected_shipping_choice": null,
    "shipping_choices": {
        "object": "list",
        "pagination": {
            "count": 0,
            "limit": 20,
            "page": 1,
            "url": "\/v1\/shipping_choices?checkout_ids%5B%5D=aa710cfd-f5a9-4918-aa03-8471a3b13808"
        },
        "data": []
    },
    "bump_amount": 0,
    "number": null,
    "pdf_url": null,
    "charge": null,
    "shipping_address_required": false,
    "tax_rate": 0,
    "tax_percent": 0,
    "tax_exclusive_amount": 0,
    "tax_inclusive_amount": 0,
    "created_at": 1714044014,
    "updated_at": 1715675812,
    "email_exists": true,
    "customer_id": "3298e10d-41f9-41a6-a65d-df21a5ca5629",
    "payment_intent_id": null,
    "payment_method_id": null
}';

// "discount": {
//     "id": "d0150555-163e-4bb9-8267-e8e6d1feb3ad",
//     "object": "discount",
//     "redeemable_status": "greater_than_max_subtotal_amount",
//     "coupon": {
//         "id": "3adac6ba-afca-4549-b39d-bb25ef20a926",
//         "object": "coupon",
//         "archived": false,
//         "archived_at": null,
//         "amount_off": null,
//         "currency": "usd",
//         "duration": "forever",
//         "duration_in_months": null,
//         "expired": false,
//         "metadata": {
//             "wp_created_by": "1"
//         },
//         "max_redemptions": null,
//         "max_redemptions_per_customer": null,
//         "max_subtotal_amount": 10000,
//         "min_subtotal_amount": null,
//         "name": "MAX20",
//         "percent_off": 20,
//         "product_ids": [],
//         "redeem_by": null,
//         "times_redeemed": 1,
//         "discarded_at": null,
//         "filter_match_type": null,
//         "filter_price_ids": [],
//         "filter_product_ids": [],
//         "filter_customer_ids": [],
//         "created_at": 1711452019,
//         "updated_at": 1714738249
//     },
//     "promotion": {
//         "id": "4c7d69f9-230c-4e89-823b-202b92ebfe16",
//         "object": "promotion",
//         "archived": false,
//         "archived_at": null,
//         "code": "MAX20",
//         "expired": false,
//         "max_redemptions": null,
//         "metadata": [],
//         "redeem_by": null,
//         "times_redeemed": 1,
//         "affiliation": null,
//         "coupon": "3adac6ba-afca-4549-b39d-bb25ef20a926",
//         "customer": null,
//         "discarded_at": null,
//         "created_at": 1711452019,
//         "updated_at": 1714738242
//     },
//     "created_at": 1715675812,
//     "updated_at": 1715675812
// },

wp_interactivity_state(
	'surecart/cart',
	array(
		'checkout'    => json_decode($checkoutJson, true)
	)
);

return 'file:./view.php';
