import { newE2EPage } from '@stencil/core/testing';

import { setResponses } from '../../../../../testing';

describe('sc-checkout', () => {
  it('renders', async () => {
    const page = await newE2EPage();
    setResponses(
      [
        {
          path: '/surecart/v1/orders',
          data: {},
        },
      ],
      page,
    );
    await page.setContent('<sc-checkout></sc-checkout>');
    const element = await page.find('sc-checkout');
    expect(element).toHaveClass('hydrated');
  });

  it('updates order summary', async () => {
    const page = await newE2EPage();
    setResponses(
      [
        {
          path: '/surecart/v1/orders',
          data: {
            id: '0df38be0-5d52-4f80-af56-0a9a6eea7998',
            object: 'order',
            amount_due: 9900,
            currency: 'usd',
            discount_amount: 0,
            email: 'wordpress@example.com',
            group_key: 'sc-checkout-114',
            live_mode: false,
            metadata: [],
            name: 'admin',
            number: '3F63337A',
            processor_data: {
              stripe: {
                account_id: 'acct_1KOoA62cow5C8zvP',
                publishable_key: 'pk_test_51FrVhTKIxBDlEhovnzFUjE1K3e8s9QInYW4a2S1BrYYgePmNIFZUCSvUY90MmD10PNh0ZxYFoxkW6P1xsfPofCYG00JTdSKWFO',
              },
            },
            return_url: 'http://localhost:8888/two-column/',
            status: 'draft',
            subtotal_amount: 9900,
            tax_amount: 0,
            tax_label: null,
            tax_status: 'tax_zone_not_found',
            total_amount: 9900,
            trial_amount: 0,
            url: 'https://staging.surecart.com/portal/orders/0df38be0-5d52-4f80-af56-0a9a6eea7998',
            billing_address: null,
            charge: null,
            customer: {
              id: 'b09dde5b-2b8d-47e1-a7b5-d9d2ed3d0a78',
              object: 'customer',
              billing_matches_shipping: true,
              email: 'wordpress@example.com',
              live_mode: false,
              name: 'Mr Rodgers',
              phone: '9202462132',
              unsubscribed: false,
              billing_address: null,
              default_payment_method: '550f460f-f599-49e7-accc-e5c792c2abf5',
              shipping_address: {
                id: 'aa21c7dd-39a7-4fa0-b135-627ac38a49a3',
                object: 'address',
                city: 'Monona',
                country: 'US',
                line_1: '303 Panther Trl',
                line_2: '',
                name: null,
                postal_code: '53716',
                state: 'WI',
                created_at: 1644966839,
                updated_at: 1644966839,
              },
              tax_identifier: '1f2b43c0-ee3b-4278-aff0-2caf26e587fd',
              created_at: 1644962412,
              updated_at: 1647309341,
            },
            discount: [],
            line_items: {
              object: 'list',
              pagination: { count: 1, limit: 20, page: 1, url: '/api/v1/line_items?order_ids%5B%5D=0df38be0-5d52-4f80-af56-0a9a6eea7998' },
              data: [
                {
                  id: '8ec8664d-205c-44dc-85df-f314cd27dc6d',
                  object: 'line_item',
                  ad_hoc_amount: null,
                  discount_amount: 0,
                  quantity: 1,
                  subtotal_amount: 9900,
                  tax_amount: 0,
                  total_amount: 9900,
                  trial: false,
                  price: {
                    id: 'c1da4fff-35bd-4126-988f-ee9f18fdce40',
                    object: 'price',
                    ad_hoc: false,
                    ad_hoc_max_amount: null,
                    ad_hoc_min_amount: 0,
                    amount: 9900,
                    archived: false,
                    archived_at: null,
                    currency: 'usd',
                    current_version: true,
                    metadata: { wp_created_by: '1' },
                    recurring_interval: 'year',
                    recurring_interval_count: 1,
                    tax_behavior: 'exclusive',
                    trial_duration_days: null,
                    product: {
                      id: '88401b4f-ec88-4177-8fcd-b4a7bfc6f644',
                      object: 'product',
                      archived: false,
                      archived_at: null,
                      description: null,
                      image_url: null,
                      metadata: { wp_created_by: '1' },
                      metrics: { currency: 'usd', max_price_amount: 9900, min_price_amount: 1200, prices_count: 2 },
                      name: 'asdfasdf',
                      recurring: true,
                      tax_enabled: true,
                      tax_category: null,
                      product_group: null,
                      created_at: 1645131012,
                      updated_at: 1646402972,
                    },
                    created_at: 1645131952,
                    updated_at: 1646402972,
                  },
                  created_at: 1647309295,
                  updated_at: 1647309341,
                  price_id: 'c1da4fff-35bd-4126-988f-ee9f18fdce40',
                },
              ],
            },
            shipping_address: {
              id: 'd2e2b865-502d-45a4-88e4-273789919b34',
              object: 'address',
              city: '123',
              country: 'AU',
              line_1: '123',
              line_2: '',
              name: null,
              postal_code: '123',
              state: 'ACT',
              created_at: 1646862307,
              updated_at: 1647309341,
            },
            tax_identifier: null,
            created_at: 1646862298,
            updated_at: 1647309341,
            customer_id: 'b09dde5b-2b8d-47e1-a7b5-d9d2ed3d0a78',
            payment_intent_id: null,
            payment_method_id: null,
          },
        },
      ],
      page,
    );
    await page.setContent('<sc-checkout></sc-checkout>');
  });

  // it('Can be submitted', async () => {
  //   const page = await newE2EPage();
  //   await page.setContent('<sc-checkout><sc-form></sc-form></sc-checkout>');
  //   const checkout = await page.find('sc-checkout');
  //   setResponses(
  //     [
  //       {
  //         path: '/surecart/v1/orders',
  //         data: {
  //           id: '0df38be0-5d52-4f80-af56-0a9a6eea7998',
  //           object: 'order',
  //           amount_due: 9900,
  //           currency: 'usd',
  //           discount_amount: 0,
  //           email: 'wordpress@example.com',
  //           group_key: 'sc-checkout-114',
  //           live_mode: false,
  //           metadata: [],
  //           name: 'admin',
  //           number: '3F63337A',
  //           processor_data: {
  //             stripe: {
  //               account_id: 'acct_1KOoA62cow5C8zvP',
  //               publishable_key: 'pk_test_51FrVhTKIxBDlEhovnzFUjE1K3e8s9QInYW4a2S1BrYYgePmNIFZUCSvUY90MmD10PNh0ZxYFoxkW6P1xsfPofCYG00JTdSKWFO',
  //             },
  //           },
  //           return_url: 'http://localhost:8888/two-column/',
  //           status: 'draft',
  //           subtotal_amount: 9900,
  //           tax_amount: 0,
  //           tax_label: null,
  //           tax_status: 'tax_zone_not_found',
  //           total_amount: 9900,
  //           trial_amount: 0,
  //           url: 'https://staging.surecart.com/portal/orders/0df38be0-5d52-4f80-af56-0a9a6eea7998',
  //           billing_address: null,
  //           charge: null,
  //           customer: {
  //             id: 'b09dde5b-2b8d-47e1-a7b5-d9d2ed3d0a78',
  //             object: 'customer',
  //             billing_matches_shipping: true,
  //             email: 'wordpress@example.com',
  //             live_mode: false,
  //             name: 'Mr Rodgers',
  //             phone: '9202462132',
  //             unsubscribed: false,
  //             billing_address: null,
  //             default_payment_method: '550f460f-f599-49e7-accc-e5c792c2abf5',
  //             shipping_address: {
  //               id: 'aa21c7dd-39a7-4fa0-b135-627ac38a49a3',
  //               object: 'address',
  //               city: 'Monona',
  //               country: 'US',
  //               line_1: '303 Panther Trl',
  //               line_2: '',
  //               name: null,
  //               postal_code: '53716',
  //               state: 'WI',
  //               created_at: 1644966839,
  //               updated_at: 1644966839,
  //             },
  //             tax_identifier: '1f2b43c0-ee3b-4278-aff0-2caf26e587fd',
  //             created_at: 1644962412,
  //             updated_at: 1647309341,
  //           },
  //           discount: [],
  //           line_items: {
  //             object: 'list',
  //             pagination: { count: 1, limit: 20, page: 1, url: '/api/v1/line_items?order_ids%5B%5D=0df38be0-5d52-4f80-af56-0a9a6eea7998' },
  //             data: [
  //               {
  //                 id: '8ec8664d-205c-44dc-85df-f314cd27dc6d',
  //                 object: 'line_item',
  //                 ad_hoc_amount: null,
  //                 discount_amount: 0,
  //                 quantity: 1,
  //                 subtotal_amount: 9900,
  //                 tax_amount: 0,
  //                 total_amount: 9900,
  //                 trial: false,
  //                 price: {
  //                   id: 'c1da4fff-35bd-4126-988f-ee9f18fdce40',
  //                   object: 'price',
  //                   ad_hoc: false,
  //                   ad_hoc_max_amount: null,
  //                   ad_hoc_min_amount: 0,
  //                   amount: 9900,
  //                   archived: false,
  //                   archived_at: null,
  //                   currency: 'usd',
  //                   current_version: true,
  //                   metadata: { wp_created_by: '1' },
  //                   recurring_interval: 'year',
  //                   recurring_interval_count: 1,
  //                   tax_behavior: 'exclusive',
  //                   trial_duration_days: null,
  //                   product: {
  //                     id: '88401b4f-ec88-4177-8fcd-b4a7bfc6f644',
  //                     object: 'product',
  //                     archived: false,
  //                     archived_at: null,
  //                     description: null,
  //                     image_url: null,
  //                     metadata: { wp_created_by: '1' },
  //                     metrics: { currency: 'usd', max_price_amount: 9900, min_price_amount: 1200, prices_count: 2 },
  //                     name: 'asdfasdf',
  //                     recurring: true,
  //                     tax_enabled: true,
  //                     tax_category: null,
  //                     product_group: null,
  //                     created_at: 1645131012,
  //                     updated_at: 1646402972,
  //                   },
  //                   created_at: 1645131952,
  //                   updated_at: 1646402972,
  //                 },
  //                 created_at: 1647309295,
  //                 updated_at: 1647309341,
  //                 price_id: 'c1da4fff-35bd-4126-988f-ee9f18fdce40',
  //               },
  //             ],
  //           },
  //           shipping_address: {
  //             id: 'd2e2b865-502d-45a4-88e4-273789919b34',
  //             object: 'address',
  //             city: '123',
  //             country: 'AU',
  //             line_1: '123',
  //             line_2: '',
  //             name: null,
  //             postal_code: '123',
  //             state: 'ACT',
  //             created_at: 1646862307,
  //             updated_at: 1647309341,
  //           },
  //           tax_identifier: null,
  //           created_at: 1646862298,
  //           updated_at: 1647309341,
  //           customer_id: 'b09dde5b-2b8d-47e1-a7b5-d9d2ed3d0a78',
  //           payment_intent_id: null,
  //           payment_method_id: null,
  //         },
  //       },
  //     ],
  //     page,
  //   );
  //   const result = await checkout.callMethod('submit');
  //   console.log({ result });
  // });
});
