/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { CheckoutSession, ChoiceItem, Coupon, Customer, Keys, LineItemData, Price, PriceChoice, Prices, Products, ResponseError, SubscriptionStatus } from "./types";
export namespace Components {
    interface CeAlert {
        /**
          * Makes the alert closable.
         */
        "closable": boolean;
        /**
          * The length of time, in milliseconds, the alert will show before closing itself. If the user interacts with the alert before it closes (e.g. moves the mouse over it), the timer will restart. Defaults to `Infinity`.
         */
        "duration": number;
        /**
          * Hides the alert
         */
        "hide": () => Promise<void>;
        /**
          * Indicates whether or not the alert is open. You can use this in lieu of the show/hide methods.
         */
        "open": boolean;
        /**
          * Shows the alert.
         */
        "show": () => Promise<void>;
        /**
          * The type of alert.
         */
        "type": 'primary' | 'success' | 'info' | 'warning' | 'danger';
    }
    interface CeBadgeNotice {
        "label": string;
        "size": 'small' | 'medium' | 'large';
        "type": 'primary' | 'success' | 'info' | 'warning' | 'danger' | 'text';
    }
    interface CeBlockUi {
        "spinner": boolean;
        "transparent": boolean;
        "zIndex": number;
    }
    interface CeButton {
        /**
          * Draws the button in a busy state.
         */
        "busy"?: boolean;
        /**
          * Draws the button with a caret for use with dropdowns, popovers, etc.
         */
        "caret"?: boolean;
        /**
          * Draws a circle button.
         */
        "circle"?: boolean;
        /**
          * Disables the button.
         */
        "disabled"?: boolean;
        /**
          * Tells the browser to download the linked file as this filename. Only used when `href` is set.
         */
        "download": string;
        /**
          * Draws the button full-width.
         */
        "full"?: boolean;
        /**
          * When set, the underlying button will be rendered as an `<a>` with this `href` instead of a `<button>`.
         */
        "href": string;
        /**
          * Draws the button in a loading state.
         */
        "loading"?: boolean;
        /**
          * An optional name for the button. Ignored when `href` is set.
         */
        "name": string;
        /**
          * Draws an outlined button.
         */
        "outline"?: boolean;
        /**
          * Draws a pill-style button with rounded edges.
         */
        "pill"?: boolean;
        /**
          * The button's size.
         */
        "size": 'small' | 'medium' | 'large';
        /**
          * Indicates if activating the button should submit the form. Ignored when `href` is set.
         */
        "submit"?: boolean;
        /**
          * Tells the browser where to open the link. Only used when `href` is set.
         */
        "target": '_blank' | '_parent' | '_self' | '_top';
        /**
          * The button's type.
         */
        "type": 'default' | 'primary' | 'success' | 'info' | 'warning' | 'danger' | 'text';
        /**
          * An optional value for the button. Ignored when `href` is set.
         */
        "value": string;
    }
    interface CeCard {
        "borderless": boolean;
        "loading": boolean;
    }
    interface CeCheckbox {
        /**
          * Draws the checkbox in a checked state.
         */
        "checked": boolean;
        /**
          * Disables the checkbox.
         */
        "disabled": boolean;
        /**
          * Draws the checkbox in an indeterminate state.
         */
        "indeterminate": boolean;
        /**
          * This will be true when the control is in an invalid state. Validity is determined by the `required` prop.
         */
        "invalid": boolean;
        /**
          * The checkbox's name attribute.
         */
        "name": string;
        /**
          * Checks for validity and shows the browser's validation message if the control is invalid.
         */
        "reportValidity": () => Promise<boolean>;
        /**
          * Makes the checkbox a required field.
         */
        "required": boolean;
        /**
          * Removes focus from the checkbox.
         */
        "triggerBlur": () => Promise<void>;
        /**
          * Simulates a click on the checkbox.
         */
        "triggerClick": () => Promise<void>;
        /**
          * Sets focus on the checkbox.
         */
        "triggerFocus": (options?: FocusOptions) => Promise<void>;
        /**
          * The checkbox's value attribute.
         */
        "value": string;
    }
    interface CeCheckout {
        /**
          * Alignment
         */
        "alignment": 'center' | 'wide' | 'full';
        /**
          * Optionally pass a coupon.
         */
        "coupon": Coupon;
        /**
          * Currency to use for this checkout.
         */
        "currencyCode": string;
        /**
          * Stores the current customer
         */
        "customer": Customer;
        /**
          * The checkout form id
         */
        "formId": number;
        /**
          * Translation object.
         */
        "i18n": Object;
        /**
          * Publishable keys for providers
         */
        "keys": Keys;
        /**
          * Are we in test or live mode.
         */
        "mode": 'test' | 'live';
        /**
          * Where to go on success
         */
        "persistSession": boolean;
        /**
          * An array of prices to pre-fill in the form.
         */
        "prices": Array<PriceChoice>;
        /**
          * Where to go on success
         */
        "successUrl": string;
    }
    interface CeChoice {
        /**
          * Draws the choice in a checked state.
         */
        "checked": boolean;
        /**
          * Is the choice disabled
         */
        "disabled": boolean;
        /**
          * This will be true when the control is in an invalid state. Validity is determined by the `required` prop.
         */
        "invalid": boolean;
        /**
          * The choice name attribute
         */
        "name": string;
        /**
          * Checks for validity and shows the browser's validation message if the control is invalid.
         */
        "reportValidity": () => Promise<boolean>;
        /**
          * Is this required
         */
        "required": boolean;
        /**
          * Sets a custom validation message. If `message` is not empty, the field will be considered invalid.
         */
        "setCustomValidity": (message: string) => Promise<void>;
        /**
          * Show the radio/checkbox control
         */
        "showControl": boolean;
        /**
          * Show the label
         */
        "showLabel": boolean;
        /**
          * Show the price
         */
        "showPrice": boolean;
        /**
          * Simulates a click on the choice.
         */
        "triggerClick": () => Promise<void>;
        /**
          * The choice name attribute
         */
        "type": 'radio' | 'checkbox';
        /**
          * The choice value
         */
        "value": string;
    }
    interface CeChoices {
        /**
          * Number of columns on desktop
         */
        "columns": number;
        /**
          * Validation error message.
         */
        "errorMessage": string;
        /**
          * The input's help text.
         */
        "help": string;
        /**
          * Hides the fieldset and legend that surrounds the group. The label will still be read by screen readers.
         */
        "hideLabel": boolean;
        /**
          * The group label. Required for proper accessibility. Alternatively, you can use the label slot.
         */
        "label": string;
        /**
          * Required
         */
        "required": boolean;
        /**
          * Should we show the label
         */
        "showLabel": boolean;
        /**
          * Input size
         */
        "size": 'small' | 'medium' | 'large';
    }
    interface CeConsumer {
        "renderer": any;
    }
    interface CeCouponForm {
        "calculating": boolean;
        "checkoutSession": CheckoutSession;
        "error": any;
        "forceOpen": boolean;
        "label": string;
        "loading": boolean;
    }
    interface CeDivider {
    }
    interface CeDropdown {
        "clickEl"?: HTMLElement;
        /**
          * Determines whether the dropdown should hide when a menu item is selected
         */
        "closeOnSelect": boolean;
        /**
          * Indicates whether or not the dropdown is open. You can use this in lieu of the show/hide methods.
         */
        "open"?: boolean;
        /**
          * The placement of the dropdown panel
         */
        "position": 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right';
    }
    interface CeEmail {
        /**
          * The input's autofocus attribute.
         */
        "autofocus": boolean;
        /**
          * (passed from the ce-checkout component automatically)
         */
        "checkoutSession": CheckoutSession;
        /**
          * Disables the input.
         */
        "disabled": boolean;
        /**
          * Inputs focus
         */
        "hasFocus": boolean;
        /**
          * The input's help text.
         */
        "help": string;
        /**
          * This will be true when the control is in an invalid state. Validity is determined by props such as `type`, `required`, `minlength`, `maxlength`, and `pattern` using the browser's constraint validation API.
         */
        "invalid": boolean;
        /**
          * The input's label.
         */
        "label": string;
        /**
          * Draws a pill-style input with rounded edges.
         */
        "pill": boolean;
        /**
          * The input's placeholder text.
         */
        "placeholder": string;
        /**
          * Makes the input readonly.
         */
        "readonly": boolean;
        /**
          * Makes the input a required field.
         */
        "required": boolean;
        /**
          * Should we show the label
         */
        "showLabel": boolean;
        /**
          * The input's size.
         */
        "size": 'small' | 'medium' | 'large';
        /**
          * The input's value attribute.
         */
        "value": string;
    }
    interface CeExpressPayment {
        "formId": number | string;
        "keys": Keys;
        "processor": 'stripe' | 'paypal';
    }
    interface CeForm {
        /**
          * Serializes all form controls elements and returns a `FormData` object.
         */
        "getFormData": () => Promise<FormData>;
        "getFormJson": () => Promise<{}>;
        /**
          * Prevent the form from validating inputs before submitting.
         */
        "novalidate": boolean;
        /**
          * Submits the form. If all controls are valid, the `ce-submit` event will be emitted and the promise will resolve with `true`. If any form control is invalid, the promise will resolve with `false` and no event will be emitted.
         */
        "submit": () => Promise<boolean>;
        "validate": () => Promise<boolean>;
    }
    interface CeFormControl {
        /**
          * Store the error message
         */
        "errorMessage": string;
        /**
          * Display server-side validation errors.
         */
        "errors": any;
        /**
          * Help text
         */
        "help": string;
        /**
          * Help id
         */
        "helpId": string;
        /**
          * Input id.
         */
        "inputId": string;
        /**
          * Input label.
         */
        "label": string;
        /**
          * Input label id.
         */
        "labelId": string;
        /**
          * Name for the input. Used for validation errors.
         */
        "name": string;
        /**
          * Whether the input is required.
         */
        "required": boolean;
        /**
          * Show the label.
         */
        "showLabel": boolean;
        /**
          * Size of the label
         */
        "size": 'small' | 'medium' | 'large';
    }
    interface CeFormRow {
    }
    interface CeFormSection {
        "label": string;
    }
    interface CeFormatInterval {
        "every": string;
        "fallback": string;
        "interval": string;
        /**
          * The number to format.
         */
        "value": number;
    }
    interface CeFormatNumber {
        /**
          * The currency to use when formatting. Must be an ISO 4217 currency code such as `USD` or `EUR`.
         */
        "currency": string;
        /**
          * How to display the currency.
         */
        "currencyDisplay": 'symbol' | 'narrowSymbol' | 'code' | 'name';
        /**
          * The locale to use when formatting the number.
         */
        "locale": string;
        /**
          * The maximum number of fraction digits to use. Possible values are 0 - 20.
         */
        "maximumFractionDigits": number;
        /**
          * The maximum number of significant digits to use,. Possible values are 1 - 21.
         */
        "maximumSignificantDigits": number;
        /**
          * The minimum number of fraction digits to use. Possible values are 0 - 20.
         */
        "minimumFractionDigits": number;
        /**
          * The minimum number of integer digits to use. Possible values are 1 - 21.
         */
        "minimumIntegerDigits": number;
        /**
          * The minimum number of significant digits to use. Possible values are 1 - 21.
         */
        "minimumSignificantDigits": number;
        "noConvert": boolean;
        /**
          * Turns off grouping separators.
         */
        "noGrouping": boolean;
        /**
          * The formatting style to use.
         */
        "type": 'currency' | 'decimal' | 'percent';
        /**
          * The number to format.
         */
        "value": number;
    }
    interface CeHeading {
    }
    interface CeInput {
        /**
          * The input's autocomplete attribute.
         */
        "autocomplete": string;
        /**
          * The input's autocorrect attribute.
         */
        "autocorrect": string;
        /**
          * The input's autofocus attribute.
         */
        "autofocus": boolean;
        /**
          * Adds a clear button when the input is populated.
         */
        "clearable": boolean;
        /**
          * Disables the input.
         */
        "disabled": boolean;
        /**
          * Inputs focus
         */
        "hasFocus": boolean;
        /**
          * The input's help text.
         */
        "help": string;
        /**
          * Hidden
         */
        "hidden": boolean;
        /**
          * The input's inputmode attribute.
         */
        "inputmode": 'none' | 'text' | 'decimal' | 'numeric' | 'tel' | 'search' | 'email' | 'url';
        /**
          * This will be true when the control is in an invalid state. Validity is determined by props such as `type`, `required`, `minlength`, `maxlength`, and `pattern` using the browser's constraint validation API.
         */
        "invalid": boolean;
        /**
          * The input's label.
         */
        "label": string;
        /**
          * The input's maximum value.
         */
        "max": number | string;
        /**
          * The maximum length of input that will be considered valid.
         */
        "maxlength": number;
        /**
          * The input's minimum value.
         */
        "min": number | string;
        /**
          * The minimum length of input that will be considered valid.
         */
        "minlength": number;
        /**
          * The input's name attribute.
         */
        "name": string;
        /**
          * A pattern to validate input against.
         */
        "pattern": string;
        /**
          * Draws a pill-style input with rounded edges.
         */
        "pill": boolean;
        /**
          * The input's placeholder text.
         */
        "placeholder": string;
        /**
          * Makes the input readonly.
         */
        "readonly": boolean;
        "reportValidity": () => Promise<boolean>;
        /**
          * Makes the input a required field.
         */
        "required": boolean;
        /**
          * Sets a custom validation message. If `message` is not empty, the field will be considered invalid.
         */
        "setCustomValidity": (message: string) => Promise<void>;
        /**
          * Should we show the label
         */
        "showLabel": boolean;
        /**
          * The input's size.
         */
        "size": 'small' | 'medium' | 'large';
        /**
          * Enables spell checking on the input.
         */
        "spellcheck": boolean;
        /**
          * The input's step attribute.
         */
        "step": number;
        /**
          * Adds a password toggle button to password inputs.
         */
        "togglePassword": boolean;
        /**
          * Removes focus from the input.
         */
        "triggerBlur": () => Promise<void>;
        /**
          * Sets focus on the input.
         */
        "triggerFocus": (options?: FocusOptions) => Promise<void>;
        /**
          * The input's type.
         */
        "type": 'email' | 'number' | 'password' | 'search' | 'tel' | 'text' | 'url';
        /**
          * The input's value attribute.
         */
        "value": string;
    }
    interface CeLineItem {
        /**
          * Currency symbol
         */
        "currency": string;
        /**
          * Price of the item
         */
        "price": string;
    }
    interface CeLineItemTotal {
        "checkoutSession": CheckoutSession;
        "loading": boolean;
        "showCurrency": boolean;
        "size": 'large' | 'medium';
        "total": 'total' | 'subtotal';
    }
    interface CeLineItems {
        "checkoutSession": CheckoutSession;
        "editable": boolean;
        "loading": boolean;
        "lockedChoices": Array<PriceChoice>;
        "prices": Prices;
        "removable": boolean;
    }
    interface CeLineItemsProvider {
        /**
          * CheckoutSession Object
         */
        "checkoutSession": CheckoutSession;
    }
    interface CeMenu {
    }
    interface CeMenuDivider {
    }
    interface CeMenuItem {
        /**
          * Draws the item in a checked state.
         */
        "checked": boolean;
        /**
          * Draws the menu item in a disabled state.
         */
        "disabled": boolean;
        /**
          * Removes focus from the button.
         */
        "setBlur": () => Promise<void>;
        /**
          * Sets focus on the button.
         */
        "setFocus": (options?: FocusOptions) => Promise<void>;
        /**
          * A unique value to store in the menu item. This can be used as a way to identify menu items when selected.
         */
        "value": string;
    }
    interface CeMenuLabel {
    }
    interface CeOrderConfirmation {
        "checkoutSession": CheckoutSession;
    }
    interface CeOrderConfirmationLineItems {
        "checkoutSession": CheckoutSession;
        "loading": boolean;
    }
    interface CeOrderConfirmationTotals {
        "checkoutSession": CheckoutSession;
    }
    interface CeOrderSummary {
        "busy": boolean;
        "checkoutSession": CheckoutSession;
        "collapsed": boolean;
        "collapsible": boolean;
        "empty": boolean;
        "loading": boolean;
    }
    interface CePayment {
        /**
          * Checkout Session from ce-checkout.
         */
        "checkoutSession": CheckoutSession;
        /**
          * Your stripe publishable key.
         */
        "keys": Keys;
        /**
          * The input's label.
         */
        "label": string;
        /**
          * Is this created in "test" mode
         */
        "mode": 'test' | 'live';
        /**
          * Payment mode inside individual payment method (i.e. Payment Buttons)
         */
        "paymentMethod": 'stripe-payment-request' | null;
        /**
          * The current payment method for the payment
         */
        "processor": string;
        /**
          * Secure notice
         */
        "secureNotice": string;
        /**
          * Your stripe connected account id.
         */
        "stripeAccountId": string;
    }
    interface CePriceChoice {
        /**
          * Is this checked by default
         */
        "checked": boolean;
        /**
          * Session
         */
        "checkoutSession": CheckoutSession;
        /**
          * Label for the choice.
         */
        "description": string;
        /**
          * Errors from response
         */
        "error": ResponseError;
        "isAdHoc": () => Promise<boolean>;
        /**
          * Label for the choice.
         */
        "label": string;
        /**
          * Is this loading
         */
        "loading": boolean;
        /**
          * Stores the price
         */
        "price": Price;
        /**
          * Id of the price.
         */
        "priceId": string;
        /**
          * Price entities
         */
        "prices": Prices;
        /**
          * Product entity
         */
        "products": Products;
        /**
          * Default quantity
         */
        "quantity": number;
        /**
          * Show the radio/checkbox control
         */
        "showControl": boolean;
        /**
          * Show the label
         */
        "showLabel": boolean;
        /**
          * Show the price amount
         */
        "showPrice": boolean;
        /**
          * Choice Type
         */
        "type": 'checkbox' | 'radio';
    }
    interface CePriceChoices {
        /**
          * Busy
         */
        "busy": boolean;
        /**
          * Number of columns
         */
        "columns": number;
        /**
          * Selector label
         */
        "label": string;
        /**
          * Required by default
         */
        "required": boolean;
    }
    interface CePriceInput {
        /**
          * The input's autofocus attribute.
         */
        "autofocus": boolean;
        /**
          * Adds a clear button when the input is populated.
         */
        "clearable": boolean;
        /**
          * 3 letter currency code for input
         */
        "currencyCode": string;
        /**
          * Disables the input.
         */
        "disabled": boolean;
        /**
          * Inputs focus
         */
        "hasFocus": boolean;
        /**
          * The input's help text.
         */
        "help": string;
        /**
          * This will be true when the control is in an invalid state. Validity is determined by props such as `type`, `required`, `minlength`, `maxlength`, and `pattern` using the browser's constraint validation API.
         */
        "invalid": boolean;
        /**
          * The input's label.
         */
        "label": string;
        /**
          * The input's maximum value.
         */
        "max": number | string;
        /**
          * The maximum length of input that will be considered valid.
         */
        "maxlength": number;
        /**
          * The input's minimum value.
         */
        "min": number | string;
        /**
          * The minimum length of input that will be considered valid.
         */
        "minlength": number;
        /**
          * The input's name attribute.
         */
        "name": string;
        /**
          * Draws a pill-style input with rounded edges.
         */
        "pill": boolean;
        /**
          * The input's placeholder text.
         */
        "placeholder": string;
        /**
          * Makes the input readonly.
         */
        "readonly": boolean;
        "reportValidity": () => Promise<boolean>;
        /**
          * Makes the input a required field.
         */
        "required": boolean;
        /**
          * Sets a custom validation message. If `message` is not empty, the field will be considered invalid.
         */
        "setCustomValidity": (message: string) => Promise<void>;
        /**
          * Should we show the label
         */
        "showLabel": boolean;
        /**
          * The input's size.
         */
        "size": 'small' | 'medium' | 'large';
        /**
          * Removes focus from the input.
         */
        "triggerBlur": () => Promise<void>;
        /**
          * Sets focus on the input.
         */
        "triggerFocus": (options?: FocusOptions) => Promise<void>;
        /**
          * The input's value attribute.
         */
        "value": string;
    }
    interface CeProductLineItem {
        /**
          * Product monetary amount
         */
        "amount": number;
        /**
          * Currency for the product
         */
        "currency": string;
        /**
          * Can we select the quantity
         */
        "editable": boolean;
        /**
          * Url for the product image
         */
        "imageUrl": string;
        /**
          * Recurring interval (i.e. monthly, once, etc.)
         */
        "interval": string;
        /**
          * Product name
         */
        "name": string;
        /**
          * Quantity
         */
        "quantity": number;
        /**
          * Is the line item removable
         */
        "removable": boolean;
        /**
          * Trial duration days
         */
        "trialDurationDays": number;
    }
    interface CeProvider {
        "STENCIL_CONTEXT": { [key: string]: any };
    }
    interface CePurchase {
    }
    interface CeQuantitySelect {
        "clickEl"?: HTMLElement;
        "max": number;
        "min": number;
        "quantity": number;
    }
    interface CeRadio {
        /**
          * Simulates a click on the radio.
         */
        "ceClick": () => Promise<void>;
        /**
          * Draws the radio in a checked state.
         */
        "checked": boolean;
        /**
          * Is the radio disabled
         */
        "disabled": boolean;
        /**
          * This will be true when the control is in an invalid state. Validity is determined by the `required` prop.
         */
        "invalid": boolean;
        /**
          * The radios name attribute
         */
        "name": string;
        /**
          * Checks for validity and shows the browser's validation message if the control is invalid.
         */
        "reportValidity": () => Promise<boolean>;
        /**
          * Is this required
         */
        "required": boolean;
        /**
          * The radios value
         */
        "value": string;
    }
    interface CeRadioGroup {
        /**
          * The radio group label. Required for proper accessibility.
         */
        "label": string;
    }
    interface CeSecureNotice {
    }
    interface CeSelect {
        /**
          * The input's value attribute.
         */
        "choices": Array<ChoiceItem>;
        /**
          * This will be true when the control is in an invalid state. Validity is determined by props such as `type`, `required`, `minlength`, `maxlength`, and `pattern` using the browser's constraint validation API.
         */
        "invalid": boolean;
        "loading": boolean;
        /**
          * Is this open
         */
        "open": boolean;
        /**
          * Placeholder for no value
         */
        "placeholder": string;
        "reportValidity": () => Promise<boolean>;
        "required": boolean;
        /**
          * Is search enabled?
         */
        "search": boolean;
        /**
          * Placeholder for search
         */
        "searchPlaceholder": string;
        /**
          * Sets a custom validation message. If `message` is not empty, the field will be considered invalid.
         */
        "setCustomValidity": (message: string) => Promise<void>;
        /**
          * The input's value attribute.
         */
        "value": string;
    }
    interface CeSessionDetail {
        "checkoutSession": CheckoutSession;
        "fallback": string;
        "label": string;
        "loading": boolean;
        "metaKey": string;
        "value": string;
    }
    interface CeSessionProvider {
        /**
          * CheckoutSession Object
         */
        "checkoutSession": CheckoutSession;
        /**
          * Currency Code
         */
        "currencyCode": string;
        /**
          * The checkout form id
         */
        "formId": number;
        /**
          * Group id
         */
        "groupId": string;
        /**
          * Are we in test or live mode.
         */
        "mode": 'test' | 'live';
        /**
          * Should we persist the session.
         */
        "persist": boolean;
        /**
          * An array of prices to pre-fill in the form.
         */
        "prices": Array<PriceChoice>;
        /**
          * Set the checkout state
         */
        "setState": (state: string) => void;
    }
    interface CeSessionSubscription {
        "checkoutSessionId": string;
    }
    interface CeSkeleton {
        /**
          * Animation effect
         */
        "effect": 'pulse' | 'sheen' | 'none';
    }
    interface CeSpinner {
    }
    interface CeStripeElement {
        /**
          * The checkout session object for finalizing intents
         */
        "checkoutSession": CheckoutSession;
        /**
          * Whether this field is disabled
         */
        "disabled": boolean;
        /**
          * Inputs focus
         */
        "hasFocus": boolean;
        /**
          * The input's label. Alternatively, you can use the label slot.
         */
        "label": string;
        /**
          * Stripe publishable key
         */
        "publishableKey": string;
        /**
          * The input's help text. Alternatively, you can use the help-text slot.
         */
        "secureText": string;
        /**
          * Should we show the label
         */
        "showLabel": boolean;
        /**
          * The input's size.
         */
        "size": 'small' | 'medium' | 'large';
        /**
          * Your stripe connected account id.
         */
        "stripeAccountId": string;
    }
    interface CeStripePaymentRequest {
        /**
          * Amount
         */
        "amount": number;
        /**
          * Checkout Session
         */
        "checkoutSession": CheckoutSession;
        /**
          * Country
         */
        "country": string;
        /**
          * Currency
         */
        "currencyCode": string;
        "error": ResponseError | null;
        /**
          * This is required to validate the form on the server
         */
        "formId": number | string;
        /**
          * Stripe publishable key
         */
        "keys": Keys;
        /**
          * Label
         */
        "label": string;
        "paymentMethod": string;
        "prices": Prices;
        /**
          * Stripe account id
         */
        "stripeAccountId": string;
        /**
          * Payment request theme
         */
        "theme": string;
    }
    interface CeSubscriptionStatusBadge {
        /**
          * Makes the tag clearable.
         */
        "clearable": boolean;
        /**
          * Draws a pill-style tag with rounded edges.
         */
        "pill": boolean;
        /**
          * The tag's size.
         */
        "size": 'small' | 'medium' | 'large';
        /**
          * The tag's statux type.
         */
        "status": SubscriptionStatus;
    }
    interface CeSwitch {
        /**
          * Draws the switch in a checked state.
         */
        "checked": boolean;
        /**
          * Disables the switch.
         */
        "disabled": boolean;
        /**
          * This will be true when the control is in an invalid state. Validity is determined by the `required` prop.
         */
        "invalid": boolean;
        /**
          * The switch's name attribute.
         */
        "name": string;
        /**
          * Checks for validity and shows the browser's validation message if the control is invalid.
         */
        "reportValidity": () => Promise<boolean>;
        /**
          * Makes the switch a required field.
         */
        "required": boolean;
        /**
          * The switch's value attribute.
         */
        "value": string;
    }
    interface CeTag {
        /**
          * Makes the tag clearable.
         */
        "clearable": boolean;
        /**
          * Draws a pill-style tag with rounded edges.
         */
        "pill": boolean;
        /**
          * The tag's size.
         */
        "size": 'small' | 'medium' | 'large';
        /**
          * The tag's type.
         */
        "type": 'primary' | 'success' | 'info' | 'warning' | 'danger' | 'text';
    }
    interface CeText {
        "tag": 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'p';
    }
    interface CeTooltip {
        /**
          * Freeze open or closed.
         */
        "freeze": boolean;
        /**
          * Open or not
         */
        "open": boolean;
        /**
          * The tooltip's padding.
         */
        "padding": number;
        /**
          * Tooltip text
         */
        "text": string;
        /**
          * The tooltip's type.
         */
        "type": 'primary' | 'success' | 'info' | 'warning' | 'danger' | 'text';
    }
    interface CeTotal {
        "checkoutSession": CheckoutSession;
        "total": 'total' | 'subtotal';
    }
}
declare global {
    interface HTMLCeAlertElement extends Components.CeAlert, HTMLStencilElement {
    }
    var HTMLCeAlertElement: {
        prototype: HTMLCeAlertElement;
        new (): HTMLCeAlertElement;
    };
    interface HTMLCeBadgeNoticeElement extends Components.CeBadgeNotice, HTMLStencilElement {
    }
    var HTMLCeBadgeNoticeElement: {
        prototype: HTMLCeBadgeNoticeElement;
        new (): HTMLCeBadgeNoticeElement;
    };
    interface HTMLCeBlockUiElement extends Components.CeBlockUi, HTMLStencilElement {
    }
    var HTMLCeBlockUiElement: {
        prototype: HTMLCeBlockUiElement;
        new (): HTMLCeBlockUiElement;
    };
    interface HTMLCeButtonElement extends Components.CeButton, HTMLStencilElement {
    }
    var HTMLCeButtonElement: {
        prototype: HTMLCeButtonElement;
        new (): HTMLCeButtonElement;
    };
    interface HTMLCeCardElement extends Components.CeCard, HTMLStencilElement {
    }
    var HTMLCeCardElement: {
        prototype: HTMLCeCardElement;
        new (): HTMLCeCardElement;
    };
    interface HTMLCeCheckboxElement extends Components.CeCheckbox, HTMLStencilElement {
    }
    var HTMLCeCheckboxElement: {
        prototype: HTMLCeCheckboxElement;
        new (): HTMLCeCheckboxElement;
    };
    interface HTMLCeCheckoutElement extends Components.CeCheckout, HTMLStencilElement {
    }
    var HTMLCeCheckoutElement: {
        prototype: HTMLCeCheckoutElement;
        new (): HTMLCeCheckoutElement;
    };
    interface HTMLCeChoiceElement extends Components.CeChoice, HTMLStencilElement {
    }
    var HTMLCeChoiceElement: {
        prototype: HTMLCeChoiceElement;
        new (): HTMLCeChoiceElement;
    };
    interface HTMLCeChoicesElement extends Components.CeChoices, HTMLStencilElement {
    }
    var HTMLCeChoicesElement: {
        prototype: HTMLCeChoicesElement;
        new (): HTMLCeChoicesElement;
    };
    interface HTMLCeConsumerElement extends Components.CeConsumer, HTMLStencilElement {
    }
    var HTMLCeConsumerElement: {
        prototype: HTMLCeConsumerElement;
        new (): HTMLCeConsumerElement;
    };
    interface HTMLCeCouponFormElement extends Components.CeCouponForm, HTMLStencilElement {
    }
    var HTMLCeCouponFormElement: {
        prototype: HTMLCeCouponFormElement;
        new (): HTMLCeCouponFormElement;
    };
    interface HTMLCeDividerElement extends Components.CeDivider, HTMLStencilElement {
    }
    var HTMLCeDividerElement: {
        prototype: HTMLCeDividerElement;
        new (): HTMLCeDividerElement;
    };
    interface HTMLCeDropdownElement extends Components.CeDropdown, HTMLStencilElement {
    }
    var HTMLCeDropdownElement: {
        prototype: HTMLCeDropdownElement;
        new (): HTMLCeDropdownElement;
    };
    interface HTMLCeEmailElement extends Components.CeEmail, HTMLStencilElement {
    }
    var HTMLCeEmailElement: {
        prototype: HTMLCeEmailElement;
        new (): HTMLCeEmailElement;
    };
    interface HTMLCeExpressPaymentElement extends Components.CeExpressPayment, HTMLStencilElement {
    }
    var HTMLCeExpressPaymentElement: {
        prototype: HTMLCeExpressPaymentElement;
        new (): HTMLCeExpressPaymentElement;
    };
    interface HTMLCeFormElement extends Components.CeForm, HTMLStencilElement {
    }
    var HTMLCeFormElement: {
        prototype: HTMLCeFormElement;
        new (): HTMLCeFormElement;
    };
    interface HTMLCeFormControlElement extends Components.CeFormControl, HTMLStencilElement {
    }
    var HTMLCeFormControlElement: {
        prototype: HTMLCeFormControlElement;
        new (): HTMLCeFormControlElement;
    };
    interface HTMLCeFormRowElement extends Components.CeFormRow, HTMLStencilElement {
    }
    var HTMLCeFormRowElement: {
        prototype: HTMLCeFormRowElement;
        new (): HTMLCeFormRowElement;
    };
    interface HTMLCeFormSectionElement extends Components.CeFormSection, HTMLStencilElement {
    }
    var HTMLCeFormSectionElement: {
        prototype: HTMLCeFormSectionElement;
        new (): HTMLCeFormSectionElement;
    };
    interface HTMLCeFormatIntervalElement extends Components.CeFormatInterval, HTMLStencilElement {
    }
    var HTMLCeFormatIntervalElement: {
        prototype: HTMLCeFormatIntervalElement;
        new (): HTMLCeFormatIntervalElement;
    };
    interface HTMLCeFormatNumberElement extends Components.CeFormatNumber, HTMLStencilElement {
    }
    var HTMLCeFormatNumberElement: {
        prototype: HTMLCeFormatNumberElement;
        new (): HTMLCeFormatNumberElement;
    };
    interface HTMLCeHeadingElement extends Components.CeHeading, HTMLStencilElement {
    }
    var HTMLCeHeadingElement: {
        prototype: HTMLCeHeadingElement;
        new (): HTMLCeHeadingElement;
    };
    interface HTMLCeInputElement extends Components.CeInput, HTMLStencilElement {
    }
    var HTMLCeInputElement: {
        prototype: HTMLCeInputElement;
        new (): HTMLCeInputElement;
    };
    interface HTMLCeLineItemElement extends Components.CeLineItem, HTMLStencilElement {
    }
    var HTMLCeLineItemElement: {
        prototype: HTMLCeLineItemElement;
        new (): HTMLCeLineItemElement;
    };
    interface HTMLCeLineItemTotalElement extends Components.CeLineItemTotal, HTMLStencilElement {
    }
    var HTMLCeLineItemTotalElement: {
        prototype: HTMLCeLineItemTotalElement;
        new (): HTMLCeLineItemTotalElement;
    };
    interface HTMLCeLineItemsElement extends Components.CeLineItems, HTMLStencilElement {
    }
    var HTMLCeLineItemsElement: {
        prototype: HTMLCeLineItemsElement;
        new (): HTMLCeLineItemsElement;
    };
    interface HTMLCeLineItemsProviderElement extends Components.CeLineItemsProvider, HTMLStencilElement {
    }
    var HTMLCeLineItemsProviderElement: {
        prototype: HTMLCeLineItemsProviderElement;
        new (): HTMLCeLineItemsProviderElement;
    };
    interface HTMLCeMenuElement extends Components.CeMenu, HTMLStencilElement {
    }
    var HTMLCeMenuElement: {
        prototype: HTMLCeMenuElement;
        new (): HTMLCeMenuElement;
    };
    interface HTMLCeMenuDividerElement extends Components.CeMenuDivider, HTMLStencilElement {
    }
    var HTMLCeMenuDividerElement: {
        prototype: HTMLCeMenuDividerElement;
        new (): HTMLCeMenuDividerElement;
    };
    interface HTMLCeMenuItemElement extends Components.CeMenuItem, HTMLStencilElement {
    }
    var HTMLCeMenuItemElement: {
        prototype: HTMLCeMenuItemElement;
        new (): HTMLCeMenuItemElement;
    };
    interface HTMLCeMenuLabelElement extends Components.CeMenuLabel, HTMLStencilElement {
    }
    var HTMLCeMenuLabelElement: {
        prototype: HTMLCeMenuLabelElement;
        new (): HTMLCeMenuLabelElement;
    };
    interface HTMLCeOrderConfirmationElement extends Components.CeOrderConfirmation, HTMLStencilElement {
    }
    var HTMLCeOrderConfirmationElement: {
        prototype: HTMLCeOrderConfirmationElement;
        new (): HTMLCeOrderConfirmationElement;
    };
    interface HTMLCeOrderConfirmationLineItemsElement extends Components.CeOrderConfirmationLineItems, HTMLStencilElement {
    }
    var HTMLCeOrderConfirmationLineItemsElement: {
        prototype: HTMLCeOrderConfirmationLineItemsElement;
        new (): HTMLCeOrderConfirmationLineItemsElement;
    };
    interface HTMLCeOrderConfirmationTotalsElement extends Components.CeOrderConfirmationTotals, HTMLStencilElement {
    }
    var HTMLCeOrderConfirmationTotalsElement: {
        prototype: HTMLCeOrderConfirmationTotalsElement;
        new (): HTMLCeOrderConfirmationTotalsElement;
    };
    interface HTMLCeOrderSummaryElement extends Components.CeOrderSummary, HTMLStencilElement {
    }
    var HTMLCeOrderSummaryElement: {
        prototype: HTMLCeOrderSummaryElement;
        new (): HTMLCeOrderSummaryElement;
    };
    interface HTMLCePaymentElement extends Components.CePayment, HTMLStencilElement {
    }
    var HTMLCePaymentElement: {
        prototype: HTMLCePaymentElement;
        new (): HTMLCePaymentElement;
    };
    interface HTMLCePriceChoiceElement extends Components.CePriceChoice, HTMLStencilElement {
    }
    var HTMLCePriceChoiceElement: {
        prototype: HTMLCePriceChoiceElement;
        new (): HTMLCePriceChoiceElement;
    };
    interface HTMLCePriceChoicesElement extends Components.CePriceChoices, HTMLStencilElement {
    }
    var HTMLCePriceChoicesElement: {
        prototype: HTMLCePriceChoicesElement;
        new (): HTMLCePriceChoicesElement;
    };
    interface HTMLCePriceInputElement extends Components.CePriceInput, HTMLStencilElement {
    }
    var HTMLCePriceInputElement: {
        prototype: HTMLCePriceInputElement;
        new (): HTMLCePriceInputElement;
    };
    interface HTMLCeProductLineItemElement extends Components.CeProductLineItem, HTMLStencilElement {
    }
    var HTMLCeProductLineItemElement: {
        prototype: HTMLCeProductLineItemElement;
        new (): HTMLCeProductLineItemElement;
    };
    interface HTMLCeProviderElement extends Components.CeProvider, HTMLStencilElement {
    }
    var HTMLCeProviderElement: {
        prototype: HTMLCeProviderElement;
        new (): HTMLCeProviderElement;
    };
    interface HTMLCePurchaseElement extends Components.CePurchase, HTMLStencilElement {
    }
    var HTMLCePurchaseElement: {
        prototype: HTMLCePurchaseElement;
        new (): HTMLCePurchaseElement;
    };
    interface HTMLCeQuantitySelectElement extends Components.CeQuantitySelect, HTMLStencilElement {
    }
    var HTMLCeQuantitySelectElement: {
        prototype: HTMLCeQuantitySelectElement;
        new (): HTMLCeQuantitySelectElement;
    };
    interface HTMLCeRadioElement extends Components.CeRadio, HTMLStencilElement {
    }
    var HTMLCeRadioElement: {
        prototype: HTMLCeRadioElement;
        new (): HTMLCeRadioElement;
    };
    interface HTMLCeRadioGroupElement extends Components.CeRadioGroup, HTMLStencilElement {
    }
    var HTMLCeRadioGroupElement: {
        prototype: HTMLCeRadioGroupElement;
        new (): HTMLCeRadioGroupElement;
    };
    interface HTMLCeSecureNoticeElement extends Components.CeSecureNotice, HTMLStencilElement {
    }
    var HTMLCeSecureNoticeElement: {
        prototype: HTMLCeSecureNoticeElement;
        new (): HTMLCeSecureNoticeElement;
    };
    interface HTMLCeSelectElement extends Components.CeSelect, HTMLStencilElement {
    }
    var HTMLCeSelectElement: {
        prototype: HTMLCeSelectElement;
        new (): HTMLCeSelectElement;
    };
    interface HTMLCeSessionDetailElement extends Components.CeSessionDetail, HTMLStencilElement {
    }
    var HTMLCeSessionDetailElement: {
        prototype: HTMLCeSessionDetailElement;
        new (): HTMLCeSessionDetailElement;
    };
    interface HTMLCeSessionProviderElement extends Components.CeSessionProvider, HTMLStencilElement {
    }
    var HTMLCeSessionProviderElement: {
        prototype: HTMLCeSessionProviderElement;
        new (): HTMLCeSessionProviderElement;
    };
    interface HTMLCeSessionSubscriptionElement extends Components.CeSessionSubscription, HTMLStencilElement {
    }
    var HTMLCeSessionSubscriptionElement: {
        prototype: HTMLCeSessionSubscriptionElement;
        new (): HTMLCeSessionSubscriptionElement;
    };
    interface HTMLCeSkeletonElement extends Components.CeSkeleton, HTMLStencilElement {
    }
    var HTMLCeSkeletonElement: {
        prototype: HTMLCeSkeletonElement;
        new (): HTMLCeSkeletonElement;
    };
    interface HTMLCeSpinnerElement extends Components.CeSpinner, HTMLStencilElement {
    }
    var HTMLCeSpinnerElement: {
        prototype: HTMLCeSpinnerElement;
        new (): HTMLCeSpinnerElement;
    };
    interface HTMLCeStripeElementElement extends Components.CeStripeElement, HTMLStencilElement {
    }
    var HTMLCeStripeElementElement: {
        prototype: HTMLCeStripeElementElement;
        new (): HTMLCeStripeElementElement;
    };
    interface HTMLCeStripePaymentRequestElement extends Components.CeStripePaymentRequest, HTMLStencilElement {
    }
    var HTMLCeStripePaymentRequestElement: {
        prototype: HTMLCeStripePaymentRequestElement;
        new (): HTMLCeStripePaymentRequestElement;
    };
    interface HTMLCeSubscriptionStatusBadgeElement extends Components.CeSubscriptionStatusBadge, HTMLStencilElement {
    }
    var HTMLCeSubscriptionStatusBadgeElement: {
        prototype: HTMLCeSubscriptionStatusBadgeElement;
        new (): HTMLCeSubscriptionStatusBadgeElement;
    };
    interface HTMLCeSwitchElement extends Components.CeSwitch, HTMLStencilElement {
    }
    var HTMLCeSwitchElement: {
        prototype: HTMLCeSwitchElement;
        new (): HTMLCeSwitchElement;
    };
    interface HTMLCeTagElement extends Components.CeTag, HTMLStencilElement {
    }
    var HTMLCeTagElement: {
        prototype: HTMLCeTagElement;
        new (): HTMLCeTagElement;
    };
    interface HTMLCeTextElement extends Components.CeText, HTMLStencilElement {
    }
    var HTMLCeTextElement: {
        prototype: HTMLCeTextElement;
        new (): HTMLCeTextElement;
    };
    interface HTMLCeTooltipElement extends Components.CeTooltip, HTMLStencilElement {
    }
    var HTMLCeTooltipElement: {
        prototype: HTMLCeTooltipElement;
        new (): HTMLCeTooltipElement;
    };
    interface HTMLCeTotalElement extends Components.CeTotal, HTMLStencilElement {
    }
    var HTMLCeTotalElement: {
        prototype: HTMLCeTotalElement;
        new (): HTMLCeTotalElement;
    };
    interface HTMLElementTagNameMap {
        "ce-alert": HTMLCeAlertElement;
        "ce-badge-notice": HTMLCeBadgeNoticeElement;
        "ce-block-ui": HTMLCeBlockUiElement;
        "ce-button": HTMLCeButtonElement;
        "ce-card": HTMLCeCardElement;
        "ce-checkbox": HTMLCeCheckboxElement;
        "ce-checkout": HTMLCeCheckoutElement;
        "ce-choice": HTMLCeChoiceElement;
        "ce-choices": HTMLCeChoicesElement;
        "ce-consumer": HTMLCeConsumerElement;
        "ce-coupon-form": HTMLCeCouponFormElement;
        "ce-divider": HTMLCeDividerElement;
        "ce-dropdown": HTMLCeDropdownElement;
        "ce-email": HTMLCeEmailElement;
        "ce-express-payment": HTMLCeExpressPaymentElement;
        "ce-form": HTMLCeFormElement;
        "ce-form-control": HTMLCeFormControlElement;
        "ce-form-row": HTMLCeFormRowElement;
        "ce-form-section": HTMLCeFormSectionElement;
        "ce-format-interval": HTMLCeFormatIntervalElement;
        "ce-format-number": HTMLCeFormatNumberElement;
        "ce-heading": HTMLCeHeadingElement;
        "ce-input": HTMLCeInputElement;
        "ce-line-item": HTMLCeLineItemElement;
        "ce-line-item-total": HTMLCeLineItemTotalElement;
        "ce-line-items": HTMLCeLineItemsElement;
        "ce-line-items-provider": HTMLCeLineItemsProviderElement;
        "ce-menu": HTMLCeMenuElement;
        "ce-menu-divider": HTMLCeMenuDividerElement;
        "ce-menu-item": HTMLCeMenuItemElement;
        "ce-menu-label": HTMLCeMenuLabelElement;
        "ce-order-confirmation": HTMLCeOrderConfirmationElement;
        "ce-order-confirmation-line-items": HTMLCeOrderConfirmationLineItemsElement;
        "ce-order-confirmation-totals": HTMLCeOrderConfirmationTotalsElement;
        "ce-order-summary": HTMLCeOrderSummaryElement;
        "ce-payment": HTMLCePaymentElement;
        "ce-price-choice": HTMLCePriceChoiceElement;
        "ce-price-choices": HTMLCePriceChoicesElement;
        "ce-price-input": HTMLCePriceInputElement;
        "ce-product-line-item": HTMLCeProductLineItemElement;
        "ce-provider": HTMLCeProviderElement;
        "ce-purchase": HTMLCePurchaseElement;
        "ce-quantity-select": HTMLCeQuantitySelectElement;
        "ce-radio": HTMLCeRadioElement;
        "ce-radio-group": HTMLCeRadioGroupElement;
        "ce-secure-notice": HTMLCeSecureNoticeElement;
        "ce-select": HTMLCeSelectElement;
        "ce-session-detail": HTMLCeSessionDetailElement;
        "ce-session-provider": HTMLCeSessionProviderElement;
        "ce-session-subscription": HTMLCeSessionSubscriptionElement;
        "ce-skeleton": HTMLCeSkeletonElement;
        "ce-spinner": HTMLCeSpinnerElement;
        "ce-stripe-element": HTMLCeStripeElementElement;
        "ce-stripe-payment-request": HTMLCeStripePaymentRequestElement;
        "ce-subscription-status-badge": HTMLCeSubscriptionStatusBadgeElement;
        "ce-switch": HTMLCeSwitchElement;
        "ce-tag": HTMLCeTagElement;
        "ce-text": HTMLCeTextElement;
        "ce-tooltip": HTMLCeTooltipElement;
        "ce-total": HTMLCeTotalElement;
    }
}
declare namespace LocalJSX {
    interface CeAlert {
        /**
          * Makes the alert closable.
         */
        "closable"?: boolean;
        /**
          * The length of time, in milliseconds, the alert will show before closing itself. If the user interacts with the alert before it closes (e.g. moves the mouse over it), the timer will restart. Defaults to `Infinity`.
         */
        "duration"?: number;
        /**
          * When alert is hidden
         */
        "onCeHide"?: (event: CustomEvent<void>) => void;
        /**
          * When alert is shown
         */
        "onCeShow"?: (event: CustomEvent<void>) => void;
        /**
          * Indicates whether or not the alert is open. You can use this in lieu of the show/hide methods.
         */
        "open"?: boolean;
        /**
          * The type of alert.
         */
        "type"?: 'primary' | 'success' | 'info' | 'warning' | 'danger';
    }
    interface CeBadgeNotice {
        "label"?: string;
        "size"?: 'small' | 'medium' | 'large';
        "type"?: 'primary' | 'success' | 'info' | 'warning' | 'danger' | 'text';
    }
    interface CeBlockUi {
        "spinner"?: boolean;
        "transparent"?: boolean;
        "zIndex"?: number;
    }
    interface CeButton {
        /**
          * Draws the button in a busy state.
         */
        "busy"?: boolean;
        /**
          * Draws the button with a caret for use with dropdowns, popovers, etc.
         */
        "caret"?: boolean;
        /**
          * Draws a circle button.
         */
        "circle"?: boolean;
        /**
          * Disables the button.
         */
        "disabled"?: boolean;
        /**
          * Tells the browser to download the linked file as this filename. Only used when `href` is set.
         */
        "download"?: string;
        /**
          * Draws the button full-width.
         */
        "full"?: boolean;
        /**
          * When set, the underlying button will be rendered as an `<a>` with this `href` instead of a `<button>`.
         */
        "href"?: string;
        /**
          * Draws the button in a loading state.
         */
        "loading"?: boolean;
        /**
          * An optional name for the button. Ignored when `href` is set.
         */
        "name"?: string;
        /**
          * Emitted when the button loses focus.
         */
        "onCeBlur"?: (event: CustomEvent<void>) => void;
        /**
          * Emitted when the button gains focus.
         */
        "onCeFocus"?: (event: CustomEvent<void>) => void;
        /**
          * Draws an outlined button.
         */
        "outline"?: boolean;
        /**
          * Draws a pill-style button with rounded edges.
         */
        "pill"?: boolean;
        /**
          * The button's size.
         */
        "size"?: 'small' | 'medium' | 'large';
        /**
          * Indicates if activating the button should submit the form. Ignored when `href` is set.
         */
        "submit"?: boolean;
        /**
          * Tells the browser where to open the link. Only used when `href` is set.
         */
        "target"?: '_blank' | '_parent' | '_self' | '_top';
        /**
          * The button's type.
         */
        "type"?: 'default' | 'primary' | 'success' | 'info' | 'warning' | 'danger' | 'text';
        /**
          * An optional value for the button. Ignored when `href` is set.
         */
        "value"?: string;
    }
    interface CeCard {
        "borderless"?: boolean;
        "loading"?: boolean;
    }
    interface CeCheckbox {
        /**
          * Draws the checkbox in a checked state.
         */
        "checked"?: boolean;
        /**
          * Disables the checkbox.
         */
        "disabled"?: boolean;
        /**
          * Draws the checkbox in an indeterminate state.
         */
        "indeterminate"?: boolean;
        /**
          * This will be true when the control is in an invalid state. Validity is determined by the `required` prop.
         */
        "invalid"?: boolean;
        /**
          * The checkbox's name attribute.
         */
        "name"?: string;
        /**
          * Emitted when the control loses focus.
         */
        "onCeBlur"?: (event: CustomEvent<void>) => void;
        /**
          * Emitted when the control's checked state changes.
         */
        "onCeChange"?: (event: CustomEvent<void>) => void;
        /**
          * Emitted when the control gains focus.
         */
        "onCeFocus"?: (event: CustomEvent<void>) => void;
        /**
          * Makes the checkbox a required field.
         */
        "required"?: boolean;
        /**
          * The checkbox's value attribute.
         */
        "value"?: string;
    }
    interface CeCheckout {
        /**
          * Alignment
         */
        "alignment"?: 'center' | 'wide' | 'full';
        /**
          * Optionally pass a coupon.
         */
        "coupon"?: Coupon;
        /**
          * Currency to use for this checkout.
         */
        "currencyCode"?: string;
        /**
          * Stores the current customer
         */
        "customer"?: Customer;
        /**
          * The checkout form id
         */
        "formId"?: number;
        /**
          * Translation object.
         */
        "i18n"?: Object;
        /**
          * Publishable keys for providers
         */
        "keys"?: Keys;
        /**
          * Are we in test or live mode.
         */
        "mode"?: 'test' | 'live';
        /**
          * Where to go on success
         */
        "persistSession"?: boolean;
        /**
          * An array of prices to pre-fill in the form.
         */
        "prices"?: Array<PriceChoice>;
        /**
          * Where to go on success
         */
        "successUrl"?: string;
    }
    interface CeChoice {
        /**
          * Draws the choice in a checked state.
         */
        "checked"?: boolean;
        /**
          * Is the choice disabled
         */
        "disabled"?: boolean;
        /**
          * This will be true when the control is in an invalid state. Validity is determined by the `required` prop.
         */
        "invalid"?: boolean;
        /**
          * The choice name attribute
         */
        "name"?: string;
        /**
          * Emitted when the control loses focus.
         */
        "onCeBlur"?: (event: CustomEvent<void>) => void;
        /**
          * Emitted when the control's checked state changes.
         */
        "onCeChange"?: (event: CustomEvent<boolean>) => void;
        /**
          * Emitted when the control gains focus.
         */
        "onCeFocus"?: (event: CustomEvent<void>) => void;
        /**
          * Is this required
         */
        "required"?: boolean;
        /**
          * Show the radio/checkbox control
         */
        "showControl"?: boolean;
        /**
          * Show the label
         */
        "showLabel"?: boolean;
        /**
          * Show the price
         */
        "showPrice"?: boolean;
        /**
          * The choice name attribute
         */
        "type"?: 'radio' | 'checkbox';
        /**
          * The choice value
         */
        "value"?: string;
    }
    interface CeChoices {
        /**
          * Number of columns on desktop
         */
        "columns"?: number;
        /**
          * Validation error message.
         */
        "errorMessage"?: string;
        /**
          * The input's help text.
         */
        "help"?: string;
        /**
          * Hides the fieldset and legend that surrounds the group. The label will still be read by screen readers.
         */
        "hideLabel"?: boolean;
        /**
          * The group label. Required for proper accessibility. Alternatively, you can use the label slot.
         */
        "label"?: string;
        /**
          * Required
         */
        "required"?: boolean;
        /**
          * Should we show the label
         */
        "showLabel"?: boolean;
        /**
          * Input size
         */
        "size"?: 'small' | 'medium' | 'large';
    }
    interface CeConsumer {
        "onMountConsumer"?: (event: CustomEvent<any>) => void;
        "renderer"?: any;
    }
    interface CeCouponForm {
        "calculating"?: boolean;
        "checkoutSession"?: CheckoutSession;
        "error"?: any;
        "forceOpen"?: boolean;
        "label"?: string;
        "loading"?: boolean;
        "onCeApplyCoupon"?: (event: CustomEvent<string>) => void;
    }
    interface CeDivider {
    }
    interface CeDropdown {
        "clickEl"?: HTMLElement;
        /**
          * Determines whether the dropdown should hide when a menu item is selected
         */
        "closeOnSelect"?: boolean;
        /**
          * Emitted when the dropdown closes. Calling `event.preventDefault()` will prevent it from being closed.
         */
        "onCeHide"?: (event: CustomEvent<void>) => void;
        /**
          * Emitted when the dropdown opens. Calling `event.preventDefault()` will prevent it from being opened.
         */
        "onCeShow"?: (event: CustomEvent<void>) => void;
        /**
          * Indicates whether or not the dropdown is open. You can use this in lieu of the show/hide methods.
         */
        "open"?: boolean;
        /**
          * The placement of the dropdown panel
         */
        "position"?: 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right';
    }
    interface CeEmail {
        /**
          * The input's autofocus attribute.
         */
        "autofocus"?: boolean;
        /**
          * (passed from the ce-checkout component automatically)
         */
        "checkoutSession"?: CheckoutSession;
        /**
          * Disables the input.
         */
        "disabled"?: boolean;
        /**
          * Inputs focus
         */
        "hasFocus"?: boolean;
        /**
          * The input's help text.
         */
        "help"?: string;
        /**
          * This will be true when the control is in an invalid state. Validity is determined by props such as `type`, `required`, `minlength`, `maxlength`, and `pattern` using the browser's constraint validation API.
         */
        "invalid"?: boolean;
        /**
          * The input's label.
         */
        "label"?: string;
        /**
          * Emitted when the control loses focus.
         */
        "onCeBlur"?: (event: CustomEvent<void>) => void;
        /**
          * Emitted when the control's value changes.
         */
        "onCeChange"?: (event: CustomEvent<void>) => void;
        /**
          * Emitted when the clear button is activated.
         */
        "onCeClear"?: (event: CustomEvent<void>) => void;
        /**
          * Emitted when the control gains focus.
         */
        "onCeFocus"?: (event: CustomEvent<void>) => void;
        /**
          * Emitted when the control receives input.
         */
        "onCeInput"?: (event: CustomEvent<void>) => void;
        "onCeUpdateCustomer"?: (event: CustomEvent<{ email: string }>) => void;
        /**
          * Draws a pill-style input with rounded edges.
         */
        "pill"?: boolean;
        /**
          * The input's placeholder text.
         */
        "placeholder"?: string;
        /**
          * Makes the input readonly.
         */
        "readonly"?: boolean;
        /**
          * Makes the input a required field.
         */
        "required"?: boolean;
        /**
          * Should we show the label
         */
        "showLabel"?: boolean;
        /**
          * The input's size.
         */
        "size"?: 'small' | 'medium' | 'large';
        /**
          * The input's value attribute.
         */
        "value"?: string;
    }
    interface CeExpressPayment {
        "formId"?: number | string;
        "keys"?: Keys;
        "processor"?: 'stripe' | 'paypal';
    }
    interface CeForm {
        /**
          * Prevent the form from validating inputs before submitting.
         */
        "novalidate"?: boolean;
        /**
          * Emitted when the form is submitted. This event will not be emitted if any form control inside of it is in an invalid state, unless the form has the `novalidate` attribute. Note that there is never a need to prevent this event, since it doen't send a GET or POST request like native forms. To "prevent" submission, use a conditional around the XHR request you use to submit the form's data with.
         */
        "onCeFormChange"?: (event: CustomEvent<Object>) => void;
        /**
          * Emitted when the form is invalid.
         */
        "onCeFormInvalid"?: (event: CustomEvent<Object>) => void;
        /**
          * Emitted when the form is submitted. This event will not be emitted if any form control inside of it is in an invalid state, unless the form has the `novalidate` attribute. Note that there is never a need to prevent this event, since it doen't send a GET or POST request like native forms. To "prevent" submission, use a conditional around the XHR request you use to submit the form's data with.
         */
        "onCeFormSubmit"?: (event: CustomEvent<void>) => void;
    }
    interface CeFormControl {
        /**
          * Store the error message
         */
        "errorMessage"?: string;
        /**
          * Display server-side validation errors.
         */
        "errors"?: any;
        /**
          * Help text
         */
        "help"?: string;
        /**
          * Help id
         */
        "helpId"?: string;
        /**
          * Input id.
         */
        "inputId"?: string;
        /**
          * Input label.
         */
        "label"?: string;
        /**
          * Input label id.
         */
        "labelId"?: string;
        /**
          * Name for the input. Used for validation errors.
         */
        "name"?: string;
        /**
          * Whether the input is required.
         */
        "required"?: boolean;
        /**
          * Show the label.
         */
        "showLabel"?: boolean;
        /**
          * Size of the label
         */
        "size"?: 'small' | 'medium' | 'large';
    }
    interface CeFormRow {
    }
    interface CeFormSection {
        "label"?: string;
    }
    interface CeFormatInterval {
        "every"?: string;
        "fallback"?: string;
        "interval"?: string;
        /**
          * The number to format.
         */
        "value"?: number;
    }
    interface CeFormatNumber {
        /**
          * The currency to use when formatting. Must be an ISO 4217 currency code such as `USD` or `EUR`.
         */
        "currency"?: string;
        /**
          * How to display the currency.
         */
        "currencyDisplay"?: 'symbol' | 'narrowSymbol' | 'code' | 'name';
        /**
          * The locale to use when formatting the number.
         */
        "locale"?: string;
        /**
          * The maximum number of fraction digits to use. Possible values are 0 - 20.
         */
        "maximumFractionDigits"?: number;
        /**
          * The maximum number of significant digits to use,. Possible values are 1 - 21.
         */
        "maximumSignificantDigits"?: number;
        /**
          * The minimum number of fraction digits to use. Possible values are 0 - 20.
         */
        "minimumFractionDigits"?: number;
        /**
          * The minimum number of integer digits to use. Possible values are 1 - 21.
         */
        "minimumIntegerDigits"?: number;
        /**
          * The minimum number of significant digits to use. Possible values are 1 - 21.
         */
        "minimumSignificantDigits"?: number;
        "noConvert"?: boolean;
        /**
          * Turns off grouping separators.
         */
        "noGrouping"?: boolean;
        /**
          * The formatting style to use.
         */
        "type"?: 'currency' | 'decimal' | 'percent';
        /**
          * The number to format.
         */
        "value"?: number;
    }
    interface CeHeading {
    }
    interface CeInput {
        /**
          * The input's autocomplete attribute.
         */
        "autocomplete"?: string;
        /**
          * The input's autocorrect attribute.
         */
        "autocorrect"?: string;
        /**
          * The input's autofocus attribute.
         */
        "autofocus"?: boolean;
        /**
          * Adds a clear button when the input is populated.
         */
        "clearable"?: boolean;
        /**
          * Disables the input.
         */
        "disabled"?: boolean;
        /**
          * Inputs focus
         */
        "hasFocus"?: boolean;
        /**
          * The input's help text.
         */
        "help"?: string;
        /**
          * Hidden
         */
        "hidden"?: boolean;
        /**
          * The input's inputmode attribute.
         */
        "inputmode"?: 'none' | 'text' | 'decimal' | 'numeric' | 'tel' | 'search' | 'email' | 'url';
        /**
          * This will be true when the control is in an invalid state. Validity is determined by props such as `type`, `required`, `minlength`, `maxlength`, and `pattern` using the browser's constraint validation API.
         */
        "invalid"?: boolean;
        /**
          * The input's label.
         */
        "label"?: string;
        /**
          * The input's maximum value.
         */
        "max"?: number | string;
        /**
          * The maximum length of input that will be considered valid.
         */
        "maxlength"?: number;
        /**
          * The input's minimum value.
         */
        "min"?: number | string;
        /**
          * The minimum length of input that will be considered valid.
         */
        "minlength"?: number;
        /**
          * The input's name attribute.
         */
        "name"?: string;
        /**
          * Emitted when the control loses focus.
         */
        "onCeBlur"?: (event: CustomEvent<void>) => void;
        /**
          * Emitted when the control's value changes.
         */
        "onCeChange"?: (event: CustomEvent<void>) => void;
        /**
          * Emitted when the clear button is activated.
         */
        "onCeClear"?: (event: CustomEvent<void>) => void;
        /**
          * Emitted when the control gains focus.
         */
        "onCeFocus"?: (event: CustomEvent<void>) => void;
        /**
          * Emitted when the control receives input.
         */
        "onCeInput"?: (event: CustomEvent<void>) => void;
        /**
          * A pattern to validate input against.
         */
        "pattern"?: string;
        /**
          * Draws a pill-style input with rounded edges.
         */
        "pill"?: boolean;
        /**
          * The input's placeholder text.
         */
        "placeholder"?: string;
        /**
          * Makes the input readonly.
         */
        "readonly"?: boolean;
        /**
          * Makes the input a required field.
         */
        "required"?: boolean;
        /**
          * Should we show the label
         */
        "showLabel"?: boolean;
        /**
          * The input's size.
         */
        "size"?: 'small' | 'medium' | 'large';
        /**
          * Enables spell checking on the input.
         */
        "spellcheck"?: boolean;
        /**
          * The input's step attribute.
         */
        "step"?: number;
        /**
          * Adds a password toggle button to password inputs.
         */
        "togglePassword"?: boolean;
        /**
          * The input's type.
         */
        "type"?: 'email' | 'number' | 'password' | 'search' | 'tel' | 'text' | 'url';
        /**
          * The input's value attribute.
         */
        "value"?: string;
    }
    interface CeLineItem {
        /**
          * Currency symbol
         */
        "currency"?: string;
        /**
          * Price of the item
         */
        "price"?: string;
    }
    interface CeLineItemTotal {
        "checkoutSession"?: CheckoutSession;
        "loading"?: boolean;
        "showCurrency"?: boolean;
        "size"?: 'large' | 'medium';
        "total"?: 'total' | 'subtotal';
    }
    interface CeLineItems {
        "checkoutSession"?: CheckoutSession;
        "editable"?: boolean;
        "loading"?: boolean;
        "lockedChoices"?: Array<PriceChoice>;
        /**
          * Remove the line item.
         */
        "onCeRemoveLineItem"?: (event: CustomEvent<LineItemData>) => void;
        /**
          * Update the line item.
         */
        "onCeUpdateLineItem"?: (event: CustomEvent<LineItemData>) => void;
        "prices"?: Prices;
        "removable"?: boolean;
    }
    interface CeLineItemsProvider {
        /**
          * CheckoutSession Object
         */
        "checkoutSession"?: CheckoutSession;
        /**
          * Update line items event
         */
        "onCeUpdateLineItems"?: (event: CustomEvent<Array<LineItemData>>) => void;
    }
    interface CeMenu {
        "onCeSelect"?: (event: CustomEvent<{ item: HTMLCeMenuItemElement }>) => void;
    }
    interface CeMenuDivider {
    }
    interface CeMenuItem {
        /**
          * Draws the item in a checked state.
         */
        "checked"?: boolean;
        /**
          * Draws the menu item in a disabled state.
         */
        "disabled"?: boolean;
        /**
          * A unique value to store in the menu item. This can be used as a way to identify menu items when selected.
         */
        "value"?: string;
    }
    interface CeMenuLabel {
    }
    interface CeOrderConfirmation {
        "checkoutSession"?: CheckoutSession;
    }
    interface CeOrderConfirmationLineItems {
        "checkoutSession"?: CheckoutSession;
        "loading"?: boolean;
    }
    interface CeOrderConfirmationTotals {
        "checkoutSession"?: CheckoutSession;
    }
    interface CeOrderSummary {
        "busy"?: boolean;
        "checkoutSession"?: CheckoutSession;
        "collapsed"?: boolean;
        "collapsible"?: boolean;
        "empty"?: boolean;
        "loading"?: boolean;
    }
    interface CePayment {
        /**
          * Checkout Session from ce-checkout.
         */
        "checkoutSession"?: CheckoutSession;
        /**
          * Your stripe publishable key.
         */
        "keys"?: Keys;
        /**
          * The input's label.
         */
        "label"?: string;
        /**
          * Is this created in "test" mode
         */
        "mode"?: 'test' | 'live';
        /**
          * Payment mode inside individual payment method (i.e. Payment Buttons)
         */
        "paymentMethod"?: 'stripe-payment-request' | null;
        /**
          * The current payment method for the payment
         */
        "processor"?: string;
        /**
          * Secure notice
         */
        "secureNotice"?: string;
        /**
          * Your stripe connected account id.
         */
        "stripeAccountId"?: string;
    }
    interface CePriceChoice {
        /**
          * Is this checked by default
         */
        "checked"?: boolean;
        /**
          * Session
         */
        "checkoutSession"?: CheckoutSession;
        /**
          * Label for the choice.
         */
        "description"?: string;
        /**
          * Errors from response
         */
        "error"?: ResponseError;
        /**
          * Label for the choice.
         */
        "label"?: string;
        /**
          * Is this loading
         */
        "loading"?: boolean;
        /**
          * Add entities
         */
        "onCeAddEntities"?: (event: CustomEvent<any>) => void;
        /**
          * Toggle line item event
         */
        "onCeRemoveLineItem"?: (event: CustomEvent<LineItemData>) => void;
        /**
          * Toggle line item event
         */
        "onCeUpdateLineItem"?: (event: CustomEvent<LineItemData>) => void;
        /**
          * Stores the price
         */
        "price"?: Price;
        /**
          * Id of the price.
         */
        "priceId"?: string;
        /**
          * Price entities
         */
        "prices"?: Prices;
        /**
          * Product entity
         */
        "products"?: Products;
        /**
          * Default quantity
         */
        "quantity"?: number;
        /**
          * Show the radio/checkbox control
         */
        "showControl"?: boolean;
        /**
          * Show the label
         */
        "showLabel"?: boolean;
        /**
          * Show the price amount
         */
        "showPrice"?: boolean;
        /**
          * Choice Type
         */
        "type"?: 'checkbox' | 'radio';
    }
    interface CePriceChoices {
        /**
          * Busy
         */
        "busy"?: boolean;
        /**
          * Number of columns
         */
        "columns"?: number;
        /**
          * Selector label
         */
        "label"?: string;
        /**
          * Toggle line item event
         */
        "onCeRemoveLineItem"?: (event: CustomEvent<LineItemData>) => void;
        /**
          * Toggle line item event
         */
        "onCeUpdateLineItem"?: (event: CustomEvent<LineItemData>) => void;
        /**
          * Required by default
         */
        "required"?: boolean;
    }
    interface CePriceInput {
        /**
          * The input's autofocus attribute.
         */
        "autofocus"?: boolean;
        /**
          * Adds a clear button when the input is populated.
         */
        "clearable"?: boolean;
        /**
          * 3 letter currency code for input
         */
        "currencyCode"?: string;
        /**
          * Disables the input.
         */
        "disabled"?: boolean;
        /**
          * Inputs focus
         */
        "hasFocus"?: boolean;
        /**
          * The input's help text.
         */
        "help"?: string;
        /**
          * This will be true when the control is in an invalid state. Validity is determined by props such as `type`, `required`, `minlength`, `maxlength`, and `pattern` using the browser's constraint validation API.
         */
        "invalid"?: boolean;
        /**
          * The input's label.
         */
        "label"?: string;
        /**
          * The input's maximum value.
         */
        "max"?: number | string;
        /**
          * The maximum length of input that will be considered valid.
         */
        "maxlength"?: number;
        /**
          * The input's minimum value.
         */
        "min"?: number | string;
        /**
          * The minimum length of input that will be considered valid.
         */
        "minlength"?: number;
        /**
          * The input's name attribute.
         */
        "name"?: string;
        /**
          * Emitted when the control's value changes.
         */
        "onCeChange"?: (event: CustomEvent<void>) => void;
        /**
          * Draws a pill-style input with rounded edges.
         */
        "pill"?: boolean;
        /**
          * The input's placeholder text.
         */
        "placeholder"?: string;
        /**
          * Makes the input readonly.
         */
        "readonly"?: boolean;
        /**
          * Makes the input a required field.
         */
        "required"?: boolean;
        /**
          * Should we show the label
         */
        "showLabel"?: boolean;
        /**
          * The input's size.
         */
        "size"?: 'small' | 'medium' | 'large';
        /**
          * The input's value attribute.
         */
        "value"?: string;
    }
    interface CeProductLineItem {
        /**
          * Product monetary amount
         */
        "amount"?: number;
        /**
          * Currency for the product
         */
        "currency"?: string;
        /**
          * Can we select the quantity
         */
        "editable"?: boolean;
        /**
          * Url for the product image
         */
        "imageUrl"?: string;
        /**
          * Recurring interval (i.e. monthly, once, etc.)
         */
        "interval"?: string;
        /**
          * Product name
         */
        "name"?: string;
        /**
          * Emitted when the quantity changes.
         */
        "onCeRemove"?: (event: CustomEvent<void>) => void;
        /**
          * Emitted when the quantity changes.
         */
        "onCeUpdateQuantity"?: (event: CustomEvent<number>) => void;
        /**
          * Quantity
         */
        "quantity"?: number;
        /**
          * Is the line item removable
         */
        "removable"?: boolean;
        /**
          * Trial duration days
         */
        "trialDurationDays"?: number;
    }
    interface CeProvider {
        "STENCIL_CONTEXT"?: { [key: string]: any };
        "onMountConsumer"?: (event: CustomEvent<any>) => void;
    }
    interface CePurchase {
    }
    interface CeQuantitySelect {
        "clickEl"?: HTMLElement;
        "max"?: number;
        "min"?: number;
        "onCeChange"?: (event: CustomEvent<number>) => void;
        "quantity"?: number;
    }
    interface CeRadio {
        /**
          * Draws the radio in a checked state.
         */
        "checked"?: boolean;
        /**
          * Is the radio disabled
         */
        "disabled"?: boolean;
        /**
          * This will be true when the control is in an invalid state. Validity is determined by the `required` prop.
         */
        "invalid"?: boolean;
        /**
          * The radios name attribute
         */
        "name"?: string;
        /**
          * Emitted when the control loses focus.
         */
        "onCeBlur"?: (event: CustomEvent<void>) => void;
        /**
          * Emitted when the control's checked state changes.
         */
        "onCeChange"?: (event: CustomEvent<void>) => void;
        /**
          * Emitted when the control gains focus.
         */
        "onCeFocus"?: (event: CustomEvent<void>) => void;
        /**
          * Is this required
         */
        "required"?: boolean;
        /**
          * The radios value
         */
        "value"?: string;
    }
    interface CeRadioGroup {
        /**
          * The radio group label. Required for proper accessibility.
         */
        "label"?: string;
    }
    interface CeSecureNotice {
    }
    interface CeSelect {
        /**
          * The input's value attribute.
         */
        "choices"?: Array<ChoiceItem>;
        /**
          * This will be true when the control is in an invalid state. Validity is determined by props such as `type`, `required`, `minlength`, `maxlength`, and `pattern` using the browser's constraint validation API.
         */
        "invalid"?: boolean;
        "loading"?: boolean;
        /**
          * Emitted when the control's value changes.
         */
        "onCeChange"?: (event: CustomEvent<void>) => void;
        /**
          * Emitted whent the components search query changes
         */
        "onCeClose"?: (event: CustomEvent<string>) => void;
        /**
          * Emitted whent the components search query changes
         */
        "onCeOpen"?: (event: CustomEvent<string>) => void;
        /**
          * Emitted whent the components search query changes
         */
        "onCeSearch"?: (event: CustomEvent<string>) => void;
        /**
          * Is this open
         */
        "open"?: boolean;
        /**
          * Placeholder for no value
         */
        "placeholder"?: string;
        "required"?: boolean;
        /**
          * Is search enabled?
         */
        "search"?: boolean;
        /**
          * Placeholder for search
         */
        "searchPlaceholder"?: string;
        /**
          * The input's value attribute.
         */
        "value"?: string;
    }
    interface CeSessionDetail {
        "checkoutSession"?: CheckoutSession;
        "fallback"?: string;
        "label"?: string;
        "loading"?: boolean;
        "metaKey"?: string;
        "value"?: string;
    }
    interface CeSessionProvider {
        /**
          * CheckoutSession Object
         */
        "checkoutSession"?: CheckoutSession;
        /**
          * Currency Code
         */
        "currencyCode"?: string;
        /**
          * The checkout form id
         */
        "formId"?: number;
        /**
          * Group id
         */
        "groupId"?: string;
        /**
          * Are we in test or live mode.
         */
        "mode"?: 'test' | 'live';
        /**
          * Update line items event
         */
        "onCeError"?: (event: CustomEvent<{ message: string; code?: string; data?: any; additional_errors?: any } | {}>) => void;
        /**
          * Set the state
         */
        "onCeSetState"?: (event: CustomEvent<string>) => void;
        /**
          * Update line items event
         */
        "onCeUpdateSession"?: (event: CustomEvent<CheckoutSession>) => void;
        /**
          * Should we persist the session.
         */
        "persist"?: boolean;
        /**
          * An array of prices to pre-fill in the form.
         */
        "prices"?: Array<PriceChoice>;
        /**
          * Set the checkout state
         */
        "setState"?: (state: string) => void;
    }
    interface CeSessionSubscription {
        "checkoutSessionId"?: string;
    }
    interface CeSkeleton {
        /**
          * Animation effect
         */
        "effect"?: 'pulse' | 'sheen' | 'none';
    }
    interface CeSpinner {
    }
    interface CeStripeElement {
        /**
          * The checkout session object for finalizing intents
         */
        "checkoutSession"?: CheckoutSession;
        /**
          * Whether this field is disabled
         */
        "disabled"?: boolean;
        /**
          * Inputs focus
         */
        "hasFocus"?: boolean;
        /**
          * The input's label. Alternatively, you can use the label slot.
         */
        "label"?: string;
        "onCePaid"?: (event: CustomEvent<void>) => void;
        "onCePayError"?: (event: CustomEvent<any>) => void;
        /**
          * Stripe publishable key
         */
        "publishableKey"?: string;
        /**
          * The input's help text. Alternatively, you can use the help-text slot.
         */
        "secureText"?: string;
        /**
          * Should we show the label
         */
        "showLabel"?: boolean;
        /**
          * The input's size.
         */
        "size"?: 'small' | 'medium' | 'large';
        /**
          * Your stripe connected account id.
         */
        "stripeAccountId"?: string;
    }
    interface CeStripePaymentRequest {
        /**
          * Amount
         */
        "amount"?: number;
        /**
          * Checkout Session
         */
        "checkoutSession"?: CheckoutSession;
        /**
          * Country
         */
        "country"?: string;
        /**
          * Currency
         */
        "currencyCode"?: string;
        "error"?: ResponseError | null;
        /**
          * This is required to validate the form on the server
         */
        "formId"?: number | string;
        /**
          * Stripe publishable key
         */
        "keys"?: Keys;
        /**
          * Label
         */
        "label"?: string;
        "onCeFormSubmit"?: (event: CustomEvent<any>) => void;
        "onCePaid"?: (event: CustomEvent<void>) => void;
        "onCePayError"?: (event: CustomEvent<any>) => void;
        "onCeSetState"?: (event: CustomEvent<string>) => void;
        "paymentMethod"?: string;
        "prices"?: Prices;
        /**
          * Stripe account id
         */
        "stripeAccountId"?: string;
        /**
          * Payment request theme
         */
        "theme"?: string;
    }
    interface CeSubscriptionStatusBadge {
        /**
          * Makes the tag clearable.
         */
        "clearable"?: boolean;
        /**
          * Draws a pill-style tag with rounded edges.
         */
        "pill"?: boolean;
        /**
          * The tag's size.
         */
        "size"?: 'small' | 'medium' | 'large';
        /**
          * The tag's statux type.
         */
        "status"?: SubscriptionStatus;
    }
    interface CeSwitch {
        /**
          * Draws the switch in a checked state.
         */
        "checked"?: boolean;
        /**
          * Disables the switch.
         */
        "disabled"?: boolean;
        /**
          * This will be true when the control is in an invalid state. Validity is determined by the `required` prop.
         */
        "invalid"?: boolean;
        /**
          * The switch's name attribute.
         */
        "name"?: string;
        /**
          * Emitted when the control loses focus.
         */
        "onCeBlur"?: (event: CustomEvent<void>) => void;
        /**
          * Emitted when the control's checked state changes.
         */
        "onCeChange"?: (event: CustomEvent<void>) => void;
        /**
          * Emitted when the control gains focus.
         */
        "onCeFocus"?: (event: CustomEvent<void>) => void;
        /**
          * Makes the switch a required field.
         */
        "required"?: boolean;
        /**
          * The switch's value attribute.
         */
        "value"?: string;
    }
    interface CeTag {
        /**
          * Makes the tag clearable.
         */
        "clearable"?: boolean;
        "onCeClear"?: (event: CustomEvent<CeTag>) => void;
        /**
          * Draws a pill-style tag with rounded edges.
         */
        "pill"?: boolean;
        /**
          * The tag's size.
         */
        "size"?: 'small' | 'medium' | 'large';
        /**
          * The tag's type.
         */
        "type"?: 'primary' | 'success' | 'info' | 'warning' | 'danger' | 'text';
    }
    interface CeText {
        "tag"?: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'p';
    }
    interface CeTooltip {
        /**
          * Freeze open or closed.
         */
        "freeze"?: boolean;
        /**
          * Open or not
         */
        "open"?: boolean;
        /**
          * The tooltip's padding.
         */
        "padding"?: number;
        /**
          * Tooltip text
         */
        "text"?: string;
        /**
          * The tooltip's type.
         */
        "type"?: 'primary' | 'success' | 'info' | 'warning' | 'danger' | 'text';
    }
    interface CeTotal {
        "checkoutSession"?: CheckoutSession;
        "total"?: 'total' | 'subtotal';
    }
    interface IntrinsicElements {
        "ce-alert": CeAlert;
        "ce-badge-notice": CeBadgeNotice;
        "ce-block-ui": CeBlockUi;
        "ce-button": CeButton;
        "ce-card": CeCard;
        "ce-checkbox": CeCheckbox;
        "ce-checkout": CeCheckout;
        "ce-choice": CeChoice;
        "ce-choices": CeChoices;
        "ce-consumer": CeConsumer;
        "ce-coupon-form": CeCouponForm;
        "ce-divider": CeDivider;
        "ce-dropdown": CeDropdown;
        "ce-email": CeEmail;
        "ce-express-payment": CeExpressPayment;
        "ce-form": CeForm;
        "ce-form-control": CeFormControl;
        "ce-form-row": CeFormRow;
        "ce-form-section": CeFormSection;
        "ce-format-interval": CeFormatInterval;
        "ce-format-number": CeFormatNumber;
        "ce-heading": CeHeading;
        "ce-input": CeInput;
        "ce-line-item": CeLineItem;
        "ce-line-item-total": CeLineItemTotal;
        "ce-line-items": CeLineItems;
        "ce-line-items-provider": CeLineItemsProvider;
        "ce-menu": CeMenu;
        "ce-menu-divider": CeMenuDivider;
        "ce-menu-item": CeMenuItem;
        "ce-menu-label": CeMenuLabel;
        "ce-order-confirmation": CeOrderConfirmation;
        "ce-order-confirmation-line-items": CeOrderConfirmationLineItems;
        "ce-order-confirmation-totals": CeOrderConfirmationTotals;
        "ce-order-summary": CeOrderSummary;
        "ce-payment": CePayment;
        "ce-price-choice": CePriceChoice;
        "ce-price-choices": CePriceChoices;
        "ce-price-input": CePriceInput;
        "ce-product-line-item": CeProductLineItem;
        "ce-provider": CeProvider;
        "ce-purchase": CePurchase;
        "ce-quantity-select": CeQuantitySelect;
        "ce-radio": CeRadio;
        "ce-radio-group": CeRadioGroup;
        "ce-secure-notice": CeSecureNotice;
        "ce-select": CeSelect;
        "ce-session-detail": CeSessionDetail;
        "ce-session-provider": CeSessionProvider;
        "ce-session-subscription": CeSessionSubscription;
        "ce-skeleton": CeSkeleton;
        "ce-spinner": CeSpinner;
        "ce-stripe-element": CeStripeElement;
        "ce-stripe-payment-request": CeStripePaymentRequest;
        "ce-subscription-status-badge": CeSubscriptionStatusBadge;
        "ce-switch": CeSwitch;
        "ce-tag": CeTag;
        "ce-text": CeText;
        "ce-tooltip": CeTooltip;
        "ce-total": CeTotal;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ce-alert": LocalJSX.CeAlert & JSXBase.HTMLAttributes<HTMLCeAlertElement>;
            "ce-badge-notice": LocalJSX.CeBadgeNotice & JSXBase.HTMLAttributes<HTMLCeBadgeNoticeElement>;
            "ce-block-ui": LocalJSX.CeBlockUi & JSXBase.HTMLAttributes<HTMLCeBlockUiElement>;
            "ce-button": LocalJSX.CeButton & JSXBase.HTMLAttributes<HTMLCeButtonElement>;
            "ce-card": LocalJSX.CeCard & JSXBase.HTMLAttributes<HTMLCeCardElement>;
            "ce-checkbox": LocalJSX.CeCheckbox & JSXBase.HTMLAttributes<HTMLCeCheckboxElement>;
            "ce-checkout": LocalJSX.CeCheckout & JSXBase.HTMLAttributes<HTMLCeCheckoutElement>;
            "ce-choice": LocalJSX.CeChoice & JSXBase.HTMLAttributes<HTMLCeChoiceElement>;
            "ce-choices": LocalJSX.CeChoices & JSXBase.HTMLAttributes<HTMLCeChoicesElement>;
            "ce-consumer": LocalJSX.CeConsumer & JSXBase.HTMLAttributes<HTMLCeConsumerElement>;
            "ce-coupon-form": LocalJSX.CeCouponForm & JSXBase.HTMLAttributes<HTMLCeCouponFormElement>;
            "ce-divider": LocalJSX.CeDivider & JSXBase.HTMLAttributes<HTMLCeDividerElement>;
            "ce-dropdown": LocalJSX.CeDropdown & JSXBase.HTMLAttributes<HTMLCeDropdownElement>;
            "ce-email": LocalJSX.CeEmail & JSXBase.HTMLAttributes<HTMLCeEmailElement>;
            "ce-express-payment": LocalJSX.CeExpressPayment & JSXBase.HTMLAttributes<HTMLCeExpressPaymentElement>;
            "ce-form": LocalJSX.CeForm & JSXBase.HTMLAttributes<HTMLCeFormElement>;
            "ce-form-control": LocalJSX.CeFormControl & JSXBase.HTMLAttributes<HTMLCeFormControlElement>;
            "ce-form-row": LocalJSX.CeFormRow & JSXBase.HTMLAttributes<HTMLCeFormRowElement>;
            "ce-form-section": LocalJSX.CeFormSection & JSXBase.HTMLAttributes<HTMLCeFormSectionElement>;
            "ce-format-interval": LocalJSX.CeFormatInterval & JSXBase.HTMLAttributes<HTMLCeFormatIntervalElement>;
            "ce-format-number": LocalJSX.CeFormatNumber & JSXBase.HTMLAttributes<HTMLCeFormatNumberElement>;
            "ce-heading": LocalJSX.CeHeading & JSXBase.HTMLAttributes<HTMLCeHeadingElement>;
            "ce-input": LocalJSX.CeInput & JSXBase.HTMLAttributes<HTMLCeInputElement>;
            "ce-line-item": LocalJSX.CeLineItem & JSXBase.HTMLAttributes<HTMLCeLineItemElement>;
            "ce-line-item-total": LocalJSX.CeLineItemTotal & JSXBase.HTMLAttributes<HTMLCeLineItemTotalElement>;
            "ce-line-items": LocalJSX.CeLineItems & JSXBase.HTMLAttributes<HTMLCeLineItemsElement>;
            "ce-line-items-provider": LocalJSX.CeLineItemsProvider & JSXBase.HTMLAttributes<HTMLCeLineItemsProviderElement>;
            "ce-menu": LocalJSX.CeMenu & JSXBase.HTMLAttributes<HTMLCeMenuElement>;
            "ce-menu-divider": LocalJSX.CeMenuDivider & JSXBase.HTMLAttributes<HTMLCeMenuDividerElement>;
            "ce-menu-item": LocalJSX.CeMenuItem & JSXBase.HTMLAttributes<HTMLCeMenuItemElement>;
            "ce-menu-label": LocalJSX.CeMenuLabel & JSXBase.HTMLAttributes<HTMLCeMenuLabelElement>;
            "ce-order-confirmation": LocalJSX.CeOrderConfirmation & JSXBase.HTMLAttributes<HTMLCeOrderConfirmationElement>;
            "ce-order-confirmation-line-items": LocalJSX.CeOrderConfirmationLineItems & JSXBase.HTMLAttributes<HTMLCeOrderConfirmationLineItemsElement>;
            "ce-order-confirmation-totals": LocalJSX.CeOrderConfirmationTotals & JSXBase.HTMLAttributes<HTMLCeOrderConfirmationTotalsElement>;
            "ce-order-summary": LocalJSX.CeOrderSummary & JSXBase.HTMLAttributes<HTMLCeOrderSummaryElement>;
            "ce-payment": LocalJSX.CePayment & JSXBase.HTMLAttributes<HTMLCePaymentElement>;
            "ce-price-choice": LocalJSX.CePriceChoice & JSXBase.HTMLAttributes<HTMLCePriceChoiceElement>;
            "ce-price-choices": LocalJSX.CePriceChoices & JSXBase.HTMLAttributes<HTMLCePriceChoicesElement>;
            "ce-price-input": LocalJSX.CePriceInput & JSXBase.HTMLAttributes<HTMLCePriceInputElement>;
            "ce-product-line-item": LocalJSX.CeProductLineItem & JSXBase.HTMLAttributes<HTMLCeProductLineItemElement>;
            "ce-provider": LocalJSX.CeProvider & JSXBase.HTMLAttributes<HTMLCeProviderElement>;
            "ce-purchase": LocalJSX.CePurchase & JSXBase.HTMLAttributes<HTMLCePurchaseElement>;
            "ce-quantity-select": LocalJSX.CeQuantitySelect & JSXBase.HTMLAttributes<HTMLCeQuantitySelectElement>;
            "ce-radio": LocalJSX.CeRadio & JSXBase.HTMLAttributes<HTMLCeRadioElement>;
            "ce-radio-group": LocalJSX.CeRadioGroup & JSXBase.HTMLAttributes<HTMLCeRadioGroupElement>;
            "ce-secure-notice": LocalJSX.CeSecureNotice & JSXBase.HTMLAttributes<HTMLCeSecureNoticeElement>;
            "ce-select": LocalJSX.CeSelect & JSXBase.HTMLAttributes<HTMLCeSelectElement>;
            "ce-session-detail": LocalJSX.CeSessionDetail & JSXBase.HTMLAttributes<HTMLCeSessionDetailElement>;
            "ce-session-provider": LocalJSX.CeSessionProvider & JSXBase.HTMLAttributes<HTMLCeSessionProviderElement>;
            "ce-session-subscription": LocalJSX.CeSessionSubscription & JSXBase.HTMLAttributes<HTMLCeSessionSubscriptionElement>;
            "ce-skeleton": LocalJSX.CeSkeleton & JSXBase.HTMLAttributes<HTMLCeSkeletonElement>;
            "ce-spinner": LocalJSX.CeSpinner & JSXBase.HTMLAttributes<HTMLCeSpinnerElement>;
            "ce-stripe-element": LocalJSX.CeStripeElement & JSXBase.HTMLAttributes<HTMLCeStripeElementElement>;
            "ce-stripe-payment-request": LocalJSX.CeStripePaymentRequest & JSXBase.HTMLAttributes<HTMLCeStripePaymentRequestElement>;
            "ce-subscription-status-badge": LocalJSX.CeSubscriptionStatusBadge & JSXBase.HTMLAttributes<HTMLCeSubscriptionStatusBadgeElement>;
            "ce-switch": LocalJSX.CeSwitch & JSXBase.HTMLAttributes<HTMLCeSwitchElement>;
            "ce-tag": LocalJSX.CeTag & JSXBase.HTMLAttributes<HTMLCeTagElement>;
            "ce-text": LocalJSX.CeText & JSXBase.HTMLAttributes<HTMLCeTextElement>;
            "ce-tooltip": LocalJSX.CeTooltip & JSXBase.HTMLAttributes<HTMLCeTooltipElement>;
            "ce-total": LocalJSX.CeTotal & JSXBase.HTMLAttributes<HTMLCeTotalElement>;
        }
    }
}
