/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Price } from "./types";
export namespace Components {
    interface CeButton {
        /**
          * Draws the button with a caret for use with dropdowns, popovers, etc.
         */
        "caret"?: boolean;
        /**
          * Draws a circle button.
         */
        "circle"?: boolean;
        /**
          * Disables the button.
         */
        "disabled"?: boolean;
        /**
          * Tells the browser to download the linked file as this filename. Only used when `href` is set.
         */
        "download": string;
        /**
          * Draws the button with a caret for use with dropdowns, popovers, etc.
         */
        "full"?: boolean;
        /**
          * When set, the underlying button will be rendered as an `<a>` with this `href` instead of a `<button>`.
         */
        "href": string;
        /**
          * Draws the button in a loading state.
         */
        "loading"?: boolean;
        /**
          * An optional name for the button. Ignored when `href` is set.
         */
        "name": string;
        /**
          * Draws a pill-style button with rounded edges.
         */
        "pill"?: boolean;
        /**
          * The button's size.
         */
        "size": 'small' | 'medium' | 'large';
        /**
          * Indicates if activating the button should submit the form. Ignored when `href` is set.
         */
        "submit"?: boolean;
        /**
          * Tells the browser where to open the link. Only used when `href` is set.
         */
        "target": '_blank' | '_parent' | '_self' | '_top';
        /**
          * The button's type.
         */
        "type": 'default' | 'primary' | 'success' | 'info' | 'warning' | 'danger' | 'text';
        /**
          * An optional value for the button. Ignored when `href` is set.
         */
        "value": string;
    }
    interface CeCheckbox {
        /**
          * Draws the checkbox in a checked state.
         */
        "checked": boolean;
        /**
          * Disables the checkbox.
         */
        "disabled": boolean;
        /**
          * Draws the checkbox in an indeterminate state.
         */
        "indeterminate": boolean;
        /**
          * This will be true when the control is in an invalid state. Validity is determined by the `required` prop.
         */
        "invalid": boolean;
        /**
          * The checkbox's name attribute.
         */
        "name": string;
        /**
          * Checks for validity and shows the browser's validation message if the control is invalid.
         */
        "reportValidity": () => Promise<boolean>;
        /**
          * Makes the checkbox a required field.
         */
        "required": boolean;
        /**
          * Removes focus from the checkbox.
         */
        "triggerBlur": () => Promise<void>;
        /**
          * Simulates a click on the checkbox.
         */
        "triggerClick": () => Promise<void>;
        /**
          * Sets focus on the checkbox.
         */
        "triggerFocus": (options?: FocusOptions) => Promise<void>;
        /**
          * The checkbox's value attribute.
         */
        "value": string;
    }
    interface CeCheckout {
        "priceIds": Array<string>;
        "publishableKey": string;
    }
    interface CeChoice {
        /**
          * Draws the choice in a checked state.
         */
        "checked": boolean;
        /**
          * Is the choice disabled
         */
        "disabled": boolean;
        /**
          * This will be true when the control is in an invalid state. Validity is determined by the `required` prop.
         */
        "invalid": boolean;
        /**
          * The choice name attribute
         */
        "name": string;
        /**
          * Checks for validity and shows the browser's validation message if the control is invalid.
         */
        "reportValidity": () => Promise<boolean>;
        /**
          * Is this required
         */
        "required": boolean;
        /**
          * Sets a custom validation message. If `message` is not empty, the field will be considered invalid.
         */
        "setCustomValidity": (message: string) => Promise<void>;
        /**
          * Simulates a click on the choice.
         */
        "triggerClick": () => Promise<void>;
        /**
          * The choice name attribute
         */
        "type": 'radio' | 'checkbox';
        /**
          * The choice value
         */
        "value": string;
    }
    interface CeChoices {
        "columns": number;
        /**
          * Hides the fieldset and legend that surrounds the group. The label will still be read by screen readers.
         */
        "hideLabel": boolean;
        /**
          * The group label. Required for proper accessibility. Alternatively, you can use the label slot.
         */
        "label": string;
    }
    interface CeConsumer {
        "renderer": any;
    }
    interface CeDivider {
    }
    interface CeDropdown {
        "clickEl"?: HTMLElement;
        /**
          * Determines whether the dropdown should hide when a menu item is selected
         */
        "closeOnSelect": boolean;
        /**
          * Indicates whether or not the dropdown is open. You can use this in lieu of the show/hide methods.
         */
        "open"?: boolean;
        /**
          * The placement of the dropdown panel
         */
        "position": 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right';
    }
    interface CeForm {
        /**
          * Serializes all form controls elements and returns a `FormData` object.
         */
        "getFormData": () => Promise<FormData>;
        "getFormJson": () => Promise<{ [k: string]: FormDataEntryValue; }>;
        /**
          * Prevent the form from validating inputs before submitting.
         */
        "novalidate": boolean;
        /**
          * Submits the form. If all controls are valid, the `ce-submit` event will be emitted and the promise will resolve with `true`. If any form control is invalid, the promise will resolve with `false` and no event will be emitted.
         */
        "submit": () => Promise<boolean>;
    }
    interface CeFormControl {
        "help": string;
        "helpId": string;
        "inputId": string;
        "label": string;
        "labelId": string;
        "showLabel": boolean;
        "size": 'small' | 'medium' | 'large';
    }
    interface CeFormRow {
    }
    interface CeFormSection {
        "label": string;
    }
    interface CeInput {
        /**
          * The input's autocomplete attribute.
         */
        "autocomplete": string;
        /**
          * The input's autocorrect attribute.
         */
        "autocorrect": string;
        /**
          * The input's autofocus attribute.
         */
        "autofocus": boolean;
        /**
          * Adds a clear button when the input is populated.
         */
        "clearable": boolean;
        /**
          * Disables the input.
         */
        "disabled": boolean;
        /**
          * Inputs focus
         */
        "hasFocus": boolean;
        /**
          * The input's help text.
         */
        "help": string;
        /**
          * The input's inputmode attribute.
         */
        "inputmode": 'none' | 'text' | 'decimal' | 'numeric' | 'tel' | 'search' | 'email' | 'url';
        /**
          * This will be true when the control is in an invalid state. Validity is determined by props such as `type`, `required`, `minlength`, `maxlength`, and `pattern` using the browser's constraint validation API.
         */
        "invalid": boolean;
        /**
          * The input's label.
         */
        "label": string;
        /**
          * The input's maximum value.
         */
        "max": number | string;
        /**
          * The maximum length of input that will be considered valid.
         */
        "maxlength": number;
        /**
          * The input's minimum value.
         */
        "min": number | string;
        /**
          * The minimum length of input that will be considered valid.
         */
        "minlength": number;
        /**
          * The input's name attribute.
         */
        "name": string;
        /**
          * A pattern to validate input against.
         */
        "pattern": string;
        /**
          * Draws a pill-style input with rounded edges.
         */
        "pill": boolean;
        /**
          * The input's placeholder text.
         */
        "placeholder": string;
        /**
          * Makes the input readonly.
         */
        "readonly": boolean;
        "reportValidity": () => Promise<boolean>;
        /**
          * Makes the input a required field.
         */
        "required": boolean;
        /**
          * Should we show the label
         */
        "showLabel": boolean;
        /**
          * The input's size.
         */
        "size": 'small' | 'medium' | 'large';
        /**
          * Enables spell checking on the input.
         */
        "spellcheck": boolean;
        /**
          * The input's step attribute.
         */
        "step": number;
        /**
          * Adds a password toggle button to password inputs.
         */
        "togglePassword": boolean;
        /**
          * Removes focus from the input.
         */
        "triggerBlur": () => Promise<void>;
        /**
          * Sets focus on the input.
         */
        "triggerFocus": (options?: FocusOptions) => Promise<void>;
        /**
          * The input's type.
         */
        "type": 'email' | 'number' | 'password' | 'search' | 'tel' | 'text' | 'url';
        /**
          * The input's value attribute.
         */
        "value": string;
    }
    interface CeLineItem {
        /**
          * Currency symbol
         */
        "currency": string;
        /**
          * Price of the item
         */
        "price": string;
    }
    interface CeMenu {
    }
    interface CeMenuDivider {
    }
    interface CeMenuItem {
        /**
          * Draws the item in a checked state.
         */
        "checked": boolean;
        /**
          * Draws the menu item in a disabled state.
         */
        "disabled": boolean;
        /**
          * Removes focus from the button.
         */
        "setBlur": () => Promise<void>;
        /**
          * Sets focus on the button.
         */
        "setFocus": (options?: FocusOptions) => Promise<void>;
        /**
          * A unique value to store in the menu item. This can be used as a way to identify menu items when selected.
         */
        "value": string;
    }
    interface CeOrderSummary {
    }
    interface CePaymentRequest {
    }
    interface CePriceChoices {
        "columns": number;
        "default": string;
        "loading": boolean;
        "price_ids": Array<string>;
        "prices": Array<Price>;
        "submitting": boolean;
        "type": 'radio' | 'checkbox';
    }
    interface CeProvider {
        "STENCIL_CONTEXT": { [key: string]: any };
    }
    interface CeRadio {
        /**
          * Simulates a click on the radio.
         */
        "ceClick": () => Promise<void>;
        /**
          * Draws the radio in a checked state.
         */
        "checked": boolean;
        /**
          * Is the radio disabled
         */
        "disabled": boolean;
        /**
          * This will be true when the control is in an invalid state. Validity is determined by the `required` prop.
         */
        "invalid": boolean;
        /**
          * The radios name attribute
         */
        "name": string;
        /**
          * Checks for validity and shows the browser's validation message if the control is invalid.
         */
        "reportValidity": () => Promise<boolean>;
        /**
          * Is this required
         */
        "required": boolean;
        /**
          * The radios value
         */
        "value": string;
    }
    interface CeRadioGroup {
        /**
          * The radio group label. Required for proper accessibility.
         */
        "label": string;
        /**
          * Hides the fieldset and legend that surrounds the radio group. The label will still be read by screen readers.
         */
        "noFieldset": boolean;
    }
    interface CeSecureNotice {
    }
    interface CeSelect {
        /**
          * Adds a clear button when the select is populated.
         */
        "clearable": boolean;
        /**
          * Disables the select control.
         */
        "disabled": boolean;
        /**
          * The select's help text.
         */
        "help": string;
        /**
          * This will be true when the control is in an invalid state. Validity is determined by the `required` prop.
         */
        "invalid": boolean;
        /**
          * The select's label. Alternatively, you can use the label slot.
         */
        "label": string;
        /**
          * The maximum number of tags to show when `multiple` is true. After the maximum, "+n" will be shown to indicate the number of additional items that are selected. Set to -1 to remove the limit.
         */
        "maxTagsVisible": number;
        /**
          * Enables multiselect. With this enabled, value will be an array.
         */
        "multiple": boolean;
        /**
          * The select's name.
         */
        "name": string;
        /**
          * Draws a pill-style select with rounded edges.
         */
        "pill": boolean;
        /**
          * The select's placeholder text.
         */
        "placeholder": string;
        /**
          * The select's required attribute.
         */
        "required": boolean;
        /**
          * The select's size.
         */
        "size": 'small' | 'medium' | 'large';
        /**
          * The value of the control. This will be a string or an array depending on `multiple`.
         */
        "value": string | Array<string>;
    }
    interface CeSkeleton {
        /**
          * Animation effect
         */
        "effect": 'pulse' | 'sheen' | 'none';
    }
    interface CeSpinner {
    }
    interface CeStripeElement {
        /**
          * Inputs focus
         */
        "hasFocus": boolean;
        /**
          * The input's help text. Alternatively, you can use the help-text slot.
         */
        "help": string;
        /**
          * The input's label. Alternatively, you can use the label slot.
         */
        "label": string;
        /**
          * Stripe publishable key
         */
        "publishableKey": string;
        /**
          * Should we show the label
         */
        "showLabel": boolean;
        /**
          * The input's size.
         */
        "size": 'small' | 'medium' | 'large';
    }
    interface CeStripePaymentRequest {
        /**
          * Amount
         */
        "amount": number;
        /**
          * Country
         */
        "country": string;
        /**
          * Currency
         */
        "currency": string;
        /**
          * Label
         */
        "label": string;
        /**
          * Stripe publishable key
         */
        "publishableKey": string;
        /**
          * Payment request theme
         */
        "theme": string;
    }
    interface CeSubmit {
        /**
          * Draws the button full-width
         */
        "full"?: boolean;
        /**
          * The button's size.
         */
        "size": 'small' | 'medium' | 'large';
        /**
          * Draws the button full-width
         */
        "text": string;
    }
    interface CeSwitch {
        /**
          * Draws the switch in a checked state.
         */
        "checked": boolean;
        /**
          * Disables the switch.
         */
        "disabled": boolean;
        /**
          * This will be true when the control is in an invalid state. Validity is determined by the `required` prop.
         */
        "invalid": boolean;
        /**
          * The switch's name attribute.
         */
        "name": string;
        /**
          * Checks for validity and shows the browser's validation message if the control is invalid.
         */
        "reportValidity": () => Promise<boolean>;
        /**
          * Makes the switch a required field.
         */
        "required": boolean;
        /**
          * The switch's value attribute.
         */
        "value": string;
    }
}
declare global {
    interface HTMLCeButtonElement extends Components.CeButton, HTMLStencilElement {
    }
    var HTMLCeButtonElement: {
        prototype: HTMLCeButtonElement;
        new (): HTMLCeButtonElement;
    };
    interface HTMLCeCheckboxElement extends Components.CeCheckbox, HTMLStencilElement {
    }
    var HTMLCeCheckboxElement: {
        prototype: HTMLCeCheckboxElement;
        new (): HTMLCeCheckboxElement;
    };
    interface HTMLCeCheckoutElement extends Components.CeCheckout, HTMLStencilElement {
    }
    var HTMLCeCheckoutElement: {
        prototype: HTMLCeCheckoutElement;
        new (): HTMLCeCheckoutElement;
    };
    interface HTMLCeChoiceElement extends Components.CeChoice, HTMLStencilElement {
    }
    var HTMLCeChoiceElement: {
        prototype: HTMLCeChoiceElement;
        new (): HTMLCeChoiceElement;
    };
    interface HTMLCeChoicesElement extends Components.CeChoices, HTMLStencilElement {
    }
    var HTMLCeChoicesElement: {
        prototype: HTMLCeChoicesElement;
        new (): HTMLCeChoicesElement;
    };
    interface HTMLCeConsumerElement extends Components.CeConsumer, HTMLStencilElement {
    }
    var HTMLCeConsumerElement: {
        prototype: HTMLCeConsumerElement;
        new (): HTMLCeConsumerElement;
    };
    interface HTMLCeDividerElement extends Components.CeDivider, HTMLStencilElement {
    }
    var HTMLCeDividerElement: {
        prototype: HTMLCeDividerElement;
        new (): HTMLCeDividerElement;
    };
    interface HTMLCeDropdownElement extends Components.CeDropdown, HTMLStencilElement {
    }
    var HTMLCeDropdownElement: {
        prototype: HTMLCeDropdownElement;
        new (): HTMLCeDropdownElement;
    };
    interface HTMLCeFormElement extends Components.CeForm, HTMLStencilElement {
    }
    var HTMLCeFormElement: {
        prototype: HTMLCeFormElement;
        new (): HTMLCeFormElement;
    };
    interface HTMLCeFormControlElement extends Components.CeFormControl, HTMLStencilElement {
    }
    var HTMLCeFormControlElement: {
        prototype: HTMLCeFormControlElement;
        new (): HTMLCeFormControlElement;
    };
    interface HTMLCeFormRowElement extends Components.CeFormRow, HTMLStencilElement {
    }
    var HTMLCeFormRowElement: {
        prototype: HTMLCeFormRowElement;
        new (): HTMLCeFormRowElement;
    };
    interface HTMLCeFormSectionElement extends Components.CeFormSection, HTMLStencilElement {
    }
    var HTMLCeFormSectionElement: {
        prototype: HTMLCeFormSectionElement;
        new (): HTMLCeFormSectionElement;
    };
    interface HTMLCeInputElement extends Components.CeInput, HTMLStencilElement {
    }
    var HTMLCeInputElement: {
        prototype: HTMLCeInputElement;
        new (): HTMLCeInputElement;
    };
    interface HTMLCeLineItemElement extends Components.CeLineItem, HTMLStencilElement {
    }
    var HTMLCeLineItemElement: {
        prototype: HTMLCeLineItemElement;
        new (): HTMLCeLineItemElement;
    };
    interface HTMLCeMenuElement extends Components.CeMenu, HTMLStencilElement {
    }
    var HTMLCeMenuElement: {
        prototype: HTMLCeMenuElement;
        new (): HTMLCeMenuElement;
    };
    interface HTMLCeMenuDividerElement extends Components.CeMenuDivider, HTMLStencilElement {
    }
    var HTMLCeMenuDividerElement: {
        prototype: HTMLCeMenuDividerElement;
        new (): HTMLCeMenuDividerElement;
    };
    interface HTMLCeMenuItemElement extends Components.CeMenuItem, HTMLStencilElement {
    }
    var HTMLCeMenuItemElement: {
        prototype: HTMLCeMenuItemElement;
        new (): HTMLCeMenuItemElement;
    };
    interface HTMLCeOrderSummaryElement extends Components.CeOrderSummary, HTMLStencilElement {
    }
    var HTMLCeOrderSummaryElement: {
        prototype: HTMLCeOrderSummaryElement;
        new (): HTMLCeOrderSummaryElement;
    };
    interface HTMLCePaymentRequestElement extends Components.CePaymentRequest, HTMLStencilElement {
    }
    var HTMLCePaymentRequestElement: {
        prototype: HTMLCePaymentRequestElement;
        new (): HTMLCePaymentRequestElement;
    };
    interface HTMLCePriceChoicesElement extends Components.CePriceChoices, HTMLStencilElement {
    }
    var HTMLCePriceChoicesElement: {
        prototype: HTMLCePriceChoicesElement;
        new (): HTMLCePriceChoicesElement;
    };
    interface HTMLCeProviderElement extends Components.CeProvider, HTMLStencilElement {
    }
    var HTMLCeProviderElement: {
        prototype: HTMLCeProviderElement;
        new (): HTMLCeProviderElement;
    };
    interface HTMLCeRadioElement extends Components.CeRadio, HTMLStencilElement {
    }
    var HTMLCeRadioElement: {
        prototype: HTMLCeRadioElement;
        new (): HTMLCeRadioElement;
    };
    interface HTMLCeRadioGroupElement extends Components.CeRadioGroup, HTMLStencilElement {
    }
    var HTMLCeRadioGroupElement: {
        prototype: HTMLCeRadioGroupElement;
        new (): HTMLCeRadioGroupElement;
    };
    interface HTMLCeSecureNoticeElement extends Components.CeSecureNotice, HTMLStencilElement {
    }
    var HTMLCeSecureNoticeElement: {
        prototype: HTMLCeSecureNoticeElement;
        new (): HTMLCeSecureNoticeElement;
    };
    interface HTMLCeSelectElement extends Components.CeSelect, HTMLStencilElement {
    }
    var HTMLCeSelectElement: {
        prototype: HTMLCeSelectElement;
        new (): HTMLCeSelectElement;
    };
    interface HTMLCeSkeletonElement extends Components.CeSkeleton, HTMLStencilElement {
    }
    var HTMLCeSkeletonElement: {
        prototype: HTMLCeSkeletonElement;
        new (): HTMLCeSkeletonElement;
    };
    interface HTMLCeSpinnerElement extends Components.CeSpinner, HTMLStencilElement {
    }
    var HTMLCeSpinnerElement: {
        prototype: HTMLCeSpinnerElement;
        new (): HTMLCeSpinnerElement;
    };
    interface HTMLCeStripeElementElement extends Components.CeStripeElement, HTMLStencilElement {
    }
    var HTMLCeStripeElementElement: {
        prototype: HTMLCeStripeElementElement;
        new (): HTMLCeStripeElementElement;
    };
    interface HTMLCeStripePaymentRequestElement extends Components.CeStripePaymentRequest, HTMLStencilElement {
    }
    var HTMLCeStripePaymentRequestElement: {
        prototype: HTMLCeStripePaymentRequestElement;
        new (): HTMLCeStripePaymentRequestElement;
    };
    interface HTMLCeSubmitElement extends Components.CeSubmit, HTMLStencilElement {
    }
    var HTMLCeSubmitElement: {
        prototype: HTMLCeSubmitElement;
        new (): HTMLCeSubmitElement;
    };
    interface HTMLCeSwitchElement extends Components.CeSwitch, HTMLStencilElement {
    }
    var HTMLCeSwitchElement: {
        prototype: HTMLCeSwitchElement;
        new (): HTMLCeSwitchElement;
    };
    interface HTMLElementTagNameMap {
        "ce-button": HTMLCeButtonElement;
        "ce-checkbox": HTMLCeCheckboxElement;
        "ce-checkout": HTMLCeCheckoutElement;
        "ce-choice": HTMLCeChoiceElement;
        "ce-choices": HTMLCeChoicesElement;
        "ce-consumer": HTMLCeConsumerElement;
        "ce-divider": HTMLCeDividerElement;
        "ce-dropdown": HTMLCeDropdownElement;
        "ce-form": HTMLCeFormElement;
        "ce-form-control": HTMLCeFormControlElement;
        "ce-form-row": HTMLCeFormRowElement;
        "ce-form-section": HTMLCeFormSectionElement;
        "ce-input": HTMLCeInputElement;
        "ce-line-item": HTMLCeLineItemElement;
        "ce-menu": HTMLCeMenuElement;
        "ce-menu-divider": HTMLCeMenuDividerElement;
        "ce-menu-item": HTMLCeMenuItemElement;
        "ce-order-summary": HTMLCeOrderSummaryElement;
        "ce-payment-request": HTMLCePaymentRequestElement;
        "ce-price-choices": HTMLCePriceChoicesElement;
        "ce-provider": HTMLCeProviderElement;
        "ce-radio": HTMLCeRadioElement;
        "ce-radio-group": HTMLCeRadioGroupElement;
        "ce-secure-notice": HTMLCeSecureNoticeElement;
        "ce-select": HTMLCeSelectElement;
        "ce-skeleton": HTMLCeSkeletonElement;
        "ce-spinner": HTMLCeSpinnerElement;
        "ce-stripe-element": HTMLCeStripeElementElement;
        "ce-stripe-payment-request": HTMLCeStripePaymentRequestElement;
        "ce-submit": HTMLCeSubmitElement;
        "ce-switch": HTMLCeSwitchElement;
    }
}
declare namespace LocalJSX {
    interface CeButton {
        /**
          * Draws the button with a caret for use with dropdowns, popovers, etc.
         */
        "caret"?: boolean;
        /**
          * Draws a circle button.
         */
        "circle"?: boolean;
        /**
          * Disables the button.
         */
        "disabled"?: boolean;
        /**
          * Tells the browser to download the linked file as this filename. Only used when `href` is set.
         */
        "download"?: string;
        /**
          * Draws the button with a caret for use with dropdowns, popovers, etc.
         */
        "full"?: boolean;
        /**
          * When set, the underlying button will be rendered as an `<a>` with this `href` instead of a `<button>`.
         */
        "href"?: string;
        /**
          * Draws the button in a loading state.
         */
        "loading"?: boolean;
        /**
          * An optional name for the button. Ignored when `href` is set.
         */
        "name"?: string;
        /**
          * Emitted when the button loses focus.
         */
        "onCeBlur"?: (event: CustomEvent<void>) => void;
        /**
          * Emitted when the button gains focus.
         */
        "onCeFocus"?: (event: CustomEvent<void>) => void;
        /**
          * Draws a pill-style button with rounded edges.
         */
        "pill"?: boolean;
        /**
          * The button's size.
         */
        "size"?: 'small' | 'medium' | 'large';
        /**
          * Indicates if activating the button should submit the form. Ignored when `href` is set.
         */
        "submit"?: boolean;
        /**
          * Tells the browser where to open the link. Only used when `href` is set.
         */
        "target"?: '_blank' | '_parent' | '_self' | '_top';
        /**
          * The button's type.
         */
        "type"?: 'default' | 'primary' | 'success' | 'info' | 'warning' | 'danger' | 'text';
        /**
          * An optional value for the button. Ignored when `href` is set.
         */
        "value"?: string;
    }
    interface CeCheckbox {
        /**
          * Draws the checkbox in a checked state.
         */
        "checked"?: boolean;
        /**
          * Disables the checkbox.
         */
        "disabled"?: boolean;
        /**
          * Draws the checkbox in an indeterminate state.
         */
        "indeterminate"?: boolean;
        /**
          * This will be true when the control is in an invalid state. Validity is determined by the `required` prop.
         */
        "invalid"?: boolean;
        /**
          * The checkbox's name attribute.
         */
        "name"?: string;
        /**
          * Emitted when the control loses focus.
         */
        "onCeBlur"?: (event: CustomEvent<void>) => void;
        /**
          * Emitted when the control's checked state changes.
         */
        "onCeChange"?: (event: CustomEvent<void>) => void;
        /**
          * Emitted when the control gains focus.
         */
        "onCeFocus"?: (event: CustomEvent<void>) => void;
        /**
          * Makes the checkbox a required field.
         */
        "required"?: boolean;
        /**
          * The checkbox's value attribute.
         */
        "value"?: string;
    }
    interface CeCheckout {
        "priceIds"?: Array<string>;
        "publishableKey"?: string;
    }
    interface CeChoice {
        /**
          * Draws the choice in a checked state.
         */
        "checked"?: boolean;
        /**
          * Is the choice disabled
         */
        "disabled"?: boolean;
        /**
          * This will be true when the control is in an invalid state. Validity is determined by the `required` prop.
         */
        "invalid"?: boolean;
        /**
          * The choice name attribute
         */
        "name"?: string;
        /**
          * Emitted when the control loses focus.
         */
        "onCeBlur"?: (event: CustomEvent<void>) => void;
        /**
          * Emitted when the control's checked state changes.
         */
        "onCeChange"?: (event: CustomEvent<void>) => void;
        /**
          * Emitted when the control gains focus.
         */
        "onCeFocus"?: (event: CustomEvent<void>) => void;
        /**
          * Is this required
         */
        "required"?: boolean;
        /**
          * The choice name attribute
         */
        "type"?: 'radio' | 'checkbox';
        /**
          * The choice value
         */
        "value"?: string;
    }
    interface CeChoices {
        "columns"?: number;
        /**
          * Hides the fieldset and legend that surrounds the group. The label will still be read by screen readers.
         */
        "hideLabel"?: boolean;
        /**
          * The group label. Required for proper accessibility. Alternatively, you can use the label slot.
         */
        "label"?: string;
    }
    interface CeConsumer {
        "onMountConsumer"?: (event: CustomEvent<any>) => void;
        "renderer"?: any;
    }
    interface CeDivider {
    }
    interface CeDropdown {
        "clickEl"?: HTMLElement;
        /**
          * Determines whether the dropdown should hide when a menu item is selected
         */
        "closeOnSelect"?: boolean;
        /**
          * Emitted when the dropdown closes. Calling `event.preventDefault()` will prevent it from being closed.
         */
        "onCeHide"?: (event: CustomEvent<void>) => void;
        /**
          * Emitted when the dropdown opens. Calling `event.preventDefault()` will prevent it from being opened.
         */
        "onCeShow"?: (event: CustomEvent<void>) => void;
        /**
          * Indicates whether or not the dropdown is open. You can use this in lieu of the show/hide methods.
         */
        "open"?: boolean;
        /**
          * The placement of the dropdown panel
         */
        "position"?: 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right';
    }
    interface CeForm {
        /**
          * Prevent the form from validating inputs before submitting.
         */
        "novalidate"?: boolean;
        /**
          * Emitted when the form is submitted. This event will not be emitted if any form control inside of it is in an invalid state, unless the form has the `novalidate` attribute. Note that there is never a need to prevent this event, since it doen't send a GET or POST request like native forms. To "prevent" submission, use a conditional around the XHR request you use to submit the form's data with.
         */
        "onCeSubmit"?: (event: CustomEvent<{ formData: FormData; formControls: HTMLElement[] }>) => void;
    }
    interface CeFormControl {
        "help"?: string;
        "helpId"?: string;
        "inputId"?: string;
        "label"?: string;
        "labelId"?: string;
        "showLabel"?: boolean;
        "size"?: 'small' | 'medium' | 'large';
    }
    interface CeFormRow {
    }
    interface CeFormSection {
        "label"?: string;
    }
    interface CeInput {
        /**
          * The input's autocomplete attribute.
         */
        "autocomplete"?: string;
        /**
          * The input's autocorrect attribute.
         */
        "autocorrect"?: string;
        /**
          * The input's autofocus attribute.
         */
        "autofocus"?: boolean;
        /**
          * Adds a clear button when the input is populated.
         */
        "clearable"?: boolean;
        /**
          * Disables the input.
         */
        "disabled"?: boolean;
        /**
          * Inputs focus
         */
        "hasFocus"?: boolean;
        /**
          * The input's help text.
         */
        "help"?: string;
        /**
          * The input's inputmode attribute.
         */
        "inputmode"?: 'none' | 'text' | 'decimal' | 'numeric' | 'tel' | 'search' | 'email' | 'url';
        /**
          * This will be true when the control is in an invalid state. Validity is determined by props such as `type`, `required`, `minlength`, `maxlength`, and `pattern` using the browser's constraint validation API.
         */
        "invalid"?: boolean;
        /**
          * The input's label.
         */
        "label"?: string;
        /**
          * The input's maximum value.
         */
        "max"?: number | string;
        /**
          * The maximum length of input that will be considered valid.
         */
        "maxlength"?: number;
        /**
          * The input's minimum value.
         */
        "min"?: number | string;
        /**
          * The minimum length of input that will be considered valid.
         */
        "minlength"?: number;
        /**
          * The input's name attribute.
         */
        "name"?: string;
        /**
          * Emitted when the control loses focus.
         */
        "onCeBlur"?: (event: CustomEvent<void>) => void;
        /**
          * Emitted when the control's value changes.
         */
        "onCeChange"?: (event: CustomEvent<void>) => void;
        /**
          * Emitted when the clear button is activated.
         */
        "onCeClear"?: (event: CustomEvent<void>) => void;
        /**
          * Emitted when the control gains focus.
         */
        "onCeFocus"?: (event: CustomEvent<void>) => void;
        /**
          * Emitted when the control receives input.
         */
        "onCeInput"?: (event: CustomEvent<void>) => void;
        /**
          * A pattern to validate input against.
         */
        "pattern"?: string;
        /**
          * Draws a pill-style input with rounded edges.
         */
        "pill"?: boolean;
        /**
          * The input's placeholder text.
         */
        "placeholder"?: string;
        /**
          * Makes the input readonly.
         */
        "readonly"?: boolean;
        /**
          * Makes the input a required field.
         */
        "required"?: boolean;
        /**
          * Should we show the label
         */
        "showLabel"?: boolean;
        /**
          * The input's size.
         */
        "size"?: 'small' | 'medium' | 'large';
        /**
          * Enables spell checking on the input.
         */
        "spellcheck"?: boolean;
        /**
          * The input's step attribute.
         */
        "step"?: number;
        /**
          * Adds a password toggle button to password inputs.
         */
        "togglePassword"?: boolean;
        /**
          * The input's type.
         */
        "type"?: 'email' | 'number' | 'password' | 'search' | 'tel' | 'text' | 'url';
        /**
          * The input's value attribute.
         */
        "value"?: string;
    }
    interface CeLineItem {
        /**
          * Currency symbol
         */
        "currency"?: string;
        /**
          * Price of the item
         */
        "price"?: string;
    }
    interface CeMenu {
        "onCeSelect"?: (event: CustomEvent<{ item: HTMLCeMenuItemElement }>) => void;
    }
    interface CeMenuDivider {
    }
    interface CeMenuItem {
        /**
          * Draws the item in a checked state.
         */
        "checked"?: boolean;
        /**
          * Draws the menu item in a disabled state.
         */
        "disabled"?: boolean;
        /**
          * A unique value to store in the menu item. This can be used as a way to identify menu items when selected.
         */
        "value"?: string;
    }
    interface CeOrderSummary {
    }
    interface CePaymentRequest {
    }
    interface CePriceChoices {
        "columns"?: number;
        "default"?: string;
        "loading"?: boolean;
        "price_ids"?: Array<string>;
        "prices"?: Array<Price>;
        "submitting"?: boolean;
        "type"?: 'radio' | 'checkbox';
    }
    interface CeProvider {
        "STENCIL_CONTEXT"?: { [key: string]: any };
        "onMountConsumer"?: (event: CustomEvent<any>) => void;
    }
    interface CeRadio {
        /**
          * Draws the radio in a checked state.
         */
        "checked"?: boolean;
        /**
          * Is the radio disabled
         */
        "disabled"?: boolean;
        /**
          * This will be true when the control is in an invalid state. Validity is determined by the `required` prop.
         */
        "invalid"?: boolean;
        /**
          * The radios name attribute
         */
        "name"?: string;
        /**
          * Emitted when the control loses focus.
         */
        "onCeBlur"?: (event: CustomEvent<void>) => void;
        /**
          * Emitted when the control's checked state changes.
         */
        "onCeChange"?: (event: CustomEvent<void>) => void;
        /**
          * Emitted when the control gains focus.
         */
        "onCeFocus"?: (event: CustomEvent<void>) => void;
        /**
          * Is this required
         */
        "required"?: boolean;
        /**
          * The radios value
         */
        "value"?: string;
    }
    interface CeRadioGroup {
        /**
          * The radio group label. Required for proper accessibility.
         */
        "label"?: string;
        /**
          * Hides the fieldset and legend that surrounds the radio group. The label will still be read by screen readers.
         */
        "noFieldset"?: boolean;
    }
    interface CeSecureNotice {
    }
    interface CeSelect {
        /**
          * Adds a clear button when the select is populated.
         */
        "clearable"?: boolean;
        /**
          * Disables the select control.
         */
        "disabled"?: boolean;
        /**
          * The select's help text.
         */
        "help"?: string;
        /**
          * This will be true when the control is in an invalid state. Validity is determined by the `required` prop.
         */
        "invalid"?: boolean;
        /**
          * The select's label. Alternatively, you can use the label slot.
         */
        "label"?: string;
        /**
          * The maximum number of tags to show when `multiple` is true. After the maximum, "+n" will be shown to indicate the number of additional items that are selected. Set to -1 to remove the limit.
         */
        "maxTagsVisible"?: number;
        /**
          * Enables multiselect. With this enabled, value will be an array.
         */
        "multiple"?: boolean;
        /**
          * The select's name.
         */
        "name"?: string;
        /**
          * Emitted when the control loses focus.
         */
        "onCeBlur"?: (event: CustomEvent<void>) => void;
        /**
          * Emitted when the control's value changes.
         */
        "onCeChange"?: (event: CustomEvent<void>) => void;
        /**
          * Emitted when the clear button is activated.
         */
        "onCeClear"?: (event: CustomEvent<void>) => void;
        /**
          * Emitted when the control gains focus.
         */
        "onCeFocus"?: (event: CustomEvent<void>) => void;
        /**
          * Draws a pill-style select with rounded edges.
         */
        "pill"?: boolean;
        /**
          * The select's placeholder text.
         */
        "placeholder"?: string;
        /**
          * The select's required attribute.
         */
        "required"?: boolean;
        /**
          * The select's size.
         */
        "size"?: 'small' | 'medium' | 'large';
        /**
          * The value of the control. This will be a string or an array depending on `multiple`.
         */
        "value"?: string | Array<string>;
    }
    interface CeSkeleton {
        /**
          * Animation effect
         */
        "effect"?: 'pulse' | 'sheen' | 'none';
    }
    interface CeSpinner {
    }
    interface CeStripeElement {
        /**
          * Inputs focus
         */
        "hasFocus"?: boolean;
        /**
          * The input's help text. Alternatively, you can use the help-text slot.
         */
        "help"?: string;
        /**
          * The input's label. Alternatively, you can use the label slot.
         */
        "label"?: string;
        /**
          * Stripe publishable key
         */
        "publishableKey"?: string;
        /**
          * Should we show the label
         */
        "showLabel"?: boolean;
        /**
          * The input's size.
         */
        "size"?: 'small' | 'medium' | 'large';
    }
    interface CeStripePaymentRequest {
        /**
          * Amount
         */
        "amount"?: number;
        /**
          * Country
         */
        "country"?: string;
        /**
          * Currency
         */
        "currency"?: string;
        /**
          * Label
         */
        "label"?: string;
        /**
          * Stripe publishable key
         */
        "publishableKey"?: string;
        /**
          * Payment request theme
         */
        "theme"?: string;
    }
    interface CeSubmit {
        /**
          * Draws the button full-width
         */
        "full"?: boolean;
        /**
          * The button's size.
         */
        "size"?: 'small' | 'medium' | 'large';
        /**
          * Draws the button full-width
         */
        "text"?: string;
    }
    interface CeSwitch {
        /**
          * Draws the switch in a checked state.
         */
        "checked"?: boolean;
        /**
          * Disables the switch.
         */
        "disabled"?: boolean;
        /**
          * This will be true when the control is in an invalid state. Validity is determined by the `required` prop.
         */
        "invalid"?: boolean;
        /**
          * The switch's name attribute.
         */
        "name"?: string;
        /**
          * Emitted when the control loses focus.
         */
        "onCeBlur"?: (event: CustomEvent<void>) => void;
        /**
          * Emitted when the control's checked state changes.
         */
        "onCeChange"?: (event: CustomEvent<void>) => void;
        /**
          * Emitted when the control gains focus.
         */
        "onCeFocus"?: (event: CustomEvent<void>) => void;
        /**
          * Makes the switch a required field.
         */
        "required"?: boolean;
        /**
          * The switch's value attribute.
         */
        "value"?: string;
    }
    interface IntrinsicElements {
        "ce-button": CeButton;
        "ce-checkbox": CeCheckbox;
        "ce-checkout": CeCheckout;
        "ce-choice": CeChoice;
        "ce-choices": CeChoices;
        "ce-consumer": CeConsumer;
        "ce-divider": CeDivider;
        "ce-dropdown": CeDropdown;
        "ce-form": CeForm;
        "ce-form-control": CeFormControl;
        "ce-form-row": CeFormRow;
        "ce-form-section": CeFormSection;
        "ce-input": CeInput;
        "ce-line-item": CeLineItem;
        "ce-menu": CeMenu;
        "ce-menu-divider": CeMenuDivider;
        "ce-menu-item": CeMenuItem;
        "ce-order-summary": CeOrderSummary;
        "ce-payment-request": CePaymentRequest;
        "ce-price-choices": CePriceChoices;
        "ce-provider": CeProvider;
        "ce-radio": CeRadio;
        "ce-radio-group": CeRadioGroup;
        "ce-secure-notice": CeSecureNotice;
        "ce-select": CeSelect;
        "ce-skeleton": CeSkeleton;
        "ce-spinner": CeSpinner;
        "ce-stripe-element": CeStripeElement;
        "ce-stripe-payment-request": CeStripePaymentRequest;
        "ce-submit": CeSubmit;
        "ce-switch": CeSwitch;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ce-button": LocalJSX.CeButton & JSXBase.HTMLAttributes<HTMLCeButtonElement>;
            "ce-checkbox": LocalJSX.CeCheckbox & JSXBase.HTMLAttributes<HTMLCeCheckboxElement>;
            "ce-checkout": LocalJSX.CeCheckout & JSXBase.HTMLAttributes<HTMLCeCheckoutElement>;
            "ce-choice": LocalJSX.CeChoice & JSXBase.HTMLAttributes<HTMLCeChoiceElement>;
            "ce-choices": LocalJSX.CeChoices & JSXBase.HTMLAttributes<HTMLCeChoicesElement>;
            "ce-consumer": LocalJSX.CeConsumer & JSXBase.HTMLAttributes<HTMLCeConsumerElement>;
            "ce-divider": LocalJSX.CeDivider & JSXBase.HTMLAttributes<HTMLCeDividerElement>;
            "ce-dropdown": LocalJSX.CeDropdown & JSXBase.HTMLAttributes<HTMLCeDropdownElement>;
            "ce-form": LocalJSX.CeForm & JSXBase.HTMLAttributes<HTMLCeFormElement>;
            "ce-form-control": LocalJSX.CeFormControl & JSXBase.HTMLAttributes<HTMLCeFormControlElement>;
            "ce-form-row": LocalJSX.CeFormRow & JSXBase.HTMLAttributes<HTMLCeFormRowElement>;
            "ce-form-section": LocalJSX.CeFormSection & JSXBase.HTMLAttributes<HTMLCeFormSectionElement>;
            "ce-input": LocalJSX.CeInput & JSXBase.HTMLAttributes<HTMLCeInputElement>;
            "ce-line-item": LocalJSX.CeLineItem & JSXBase.HTMLAttributes<HTMLCeLineItemElement>;
            "ce-menu": LocalJSX.CeMenu & JSXBase.HTMLAttributes<HTMLCeMenuElement>;
            "ce-menu-divider": LocalJSX.CeMenuDivider & JSXBase.HTMLAttributes<HTMLCeMenuDividerElement>;
            "ce-menu-item": LocalJSX.CeMenuItem & JSXBase.HTMLAttributes<HTMLCeMenuItemElement>;
            "ce-order-summary": LocalJSX.CeOrderSummary & JSXBase.HTMLAttributes<HTMLCeOrderSummaryElement>;
            "ce-payment-request": LocalJSX.CePaymentRequest & JSXBase.HTMLAttributes<HTMLCePaymentRequestElement>;
            "ce-price-choices": LocalJSX.CePriceChoices & JSXBase.HTMLAttributes<HTMLCePriceChoicesElement>;
            "ce-provider": LocalJSX.CeProvider & JSXBase.HTMLAttributes<HTMLCeProviderElement>;
            "ce-radio": LocalJSX.CeRadio & JSXBase.HTMLAttributes<HTMLCeRadioElement>;
            "ce-radio-group": LocalJSX.CeRadioGroup & JSXBase.HTMLAttributes<HTMLCeRadioGroupElement>;
            "ce-secure-notice": LocalJSX.CeSecureNotice & JSXBase.HTMLAttributes<HTMLCeSecureNoticeElement>;
            "ce-select": LocalJSX.CeSelect & JSXBase.HTMLAttributes<HTMLCeSelectElement>;
            "ce-skeleton": LocalJSX.CeSkeleton & JSXBase.HTMLAttributes<HTMLCeSkeletonElement>;
            "ce-spinner": LocalJSX.CeSpinner & JSXBase.HTMLAttributes<HTMLCeSpinnerElement>;
            "ce-stripe-element": LocalJSX.CeStripeElement & JSXBase.HTMLAttributes<HTMLCeStripeElementElement>;
            "ce-stripe-payment-request": LocalJSX.CeStripePaymentRequest & JSXBase.HTMLAttributes<HTMLCeStripePaymentRequestElement>;
            "ce-submit": LocalJSX.CeSubmit & JSXBase.HTMLAttributes<HTMLCeSubmitElement>;
            "ce-switch": LocalJSX.CeSwitch & JSXBase.HTMLAttributes<HTMLCeSwitchElement>;
        }
    }
}
