import { newSpecPage } from '@stencil/core/testing';
import { CeQuantitySelect } from '../ce-quantity-select';

describe('ce-quantity-select', () => {
  it('renders', async () => {
    const page = await newSpecPage({
      components: [CeQuantitySelect],
      html: `<ce-quantity-select></ce-quantity-select>`,
    });
    expect(page.root).toEqualHtml(`
    <ce-quantity-select quantity="1">
    <mock:shadow-root>
     <ce-dropdown class="quantity" style="--panel-height: 150px;">
       <div class="quantity--trigger" slot="trigger">
         Qty
         <strong>
           1
         </strong>
         <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" style="width: 10px; height: 10px;">
           <polyline points="6 9 12 15 18 9"></polyline>
         </svg>
       </div>
       <ce-menu>
         <ce-menu-item>
           1
         </ce-menu-item>
         <ce-menu-item>
           2
         </ce-menu-item>
         <ce-menu-item>
           3
         </ce-menu-item>
         <ce-menu-item>
           4
         </ce-menu-item>
         <ce-menu-item>
           5
         </ce-menu-item>
         <ce-menu-item>
           6
         </ce-menu-item>
         <ce-menu-item>
           7
         </ce-menu-item>
         <ce-menu-item>
           8
         </ce-menu-item>
         <ce-menu-item>
           9
         </ce-menu-item>
         <ce-menu-item>
           10
         </ce-menu-item>
         <ce-menu-item>
           11
         </ce-menu-item>
         <ce-menu-item>
           12
         </ce-menu-item>
         <ce-menu-item>
           13
         </ce-menu-item>
         <ce-menu-item>
           14
         </ce-menu-item>
         <ce-menu-item>
           15
         </ce-menu-item>
         <ce-menu-item>
           16
         </ce-menu-item>
         <ce-menu-item>
           17
         </ce-menu-item>
         <ce-menu-item>
           18
         </ce-menu-item>
         <ce-menu-item>
           19
         </ce-menu-item>
         <ce-menu-item>
           20
         </ce-menu-item>
         <ce-menu-item>
           21
         </ce-menu-item>
         <ce-menu-item>
           22
         </ce-menu-item>
         <ce-menu-item>
           23
         </ce-menu-item>
         <ce-menu-item>
           24
         </ce-menu-item>
         <ce-menu-item>
           25
         </ce-menu-item>
         <ce-menu-item>
           26
         </ce-menu-item>
         <ce-menu-item>
           27
         </ce-menu-item>
         <ce-menu-item>
           28
         </ce-menu-item>
         <ce-menu-item>
           29
         </ce-menu-item>
         <ce-menu-item>
           30
         </ce-menu-item>
         <ce-menu-item>
           31
         </ce-menu-item>
         <ce-menu-item>
           32
         </ce-menu-item>
         <ce-menu-item>
           33
         </ce-menu-item>
         <ce-menu-item>
           34
         </ce-menu-item>
         <ce-menu-item>
           35
         </ce-menu-item>
         <ce-menu-item>
           36
         </ce-menu-item>
         <ce-menu-item>
           37
         </ce-menu-item>
         <ce-menu-item>
           38
         </ce-menu-item>
         <ce-menu-item>
           39
         </ce-menu-item>
         <ce-menu-item>
           40
         </ce-menu-item>
         <ce-menu-item>
           41
         </ce-menu-item>
         <ce-menu-item>
           42
         </ce-menu-item>
         <ce-menu-item>
           43
         </ce-menu-item>
         <ce-menu-item>
           44
         </ce-menu-item>
         <ce-menu-item>
           45
         </ce-menu-item>
         <ce-menu-item>
           46
         </ce-menu-item>
         <ce-menu-item>
           47
         </ce-menu-item>
         <ce-menu-item>
           48
         </ce-menu-item>
         <ce-menu-item>
           49
         </ce-menu-item>
         <ce-menu-item>
           50
         </ce-menu-item>
         <ce-menu-item>
           51
         </ce-menu-item>
         <ce-menu-item>
           52
         </ce-menu-item>
         <ce-menu-item>
           53
         </ce-menu-item>
         <ce-menu-item>
           54
         </ce-menu-item>
         <ce-menu-item>
           55
         </ce-menu-item>
         <ce-menu-item>
           56
         </ce-menu-item>
         <ce-menu-item>
           57
         </ce-menu-item>
         <ce-menu-item>
           58
         </ce-menu-item>
         <ce-menu-item>
           59
         </ce-menu-item>
         <ce-menu-item>
           60
         </ce-menu-item>
         <ce-menu-item>
           61
         </ce-menu-item>
         <ce-menu-item>
           62
         </ce-menu-item>
         <ce-menu-item>
           63
         </ce-menu-item>
         <ce-menu-item>
           64
         </ce-menu-item>
         <ce-menu-item>
           65
         </ce-menu-item>
         <ce-menu-item>
           66
         </ce-menu-item>
         <ce-menu-item>
           67
         </ce-menu-item>
         <ce-menu-item>
           68
         </ce-menu-item>
         <ce-menu-item>
           69
         </ce-menu-item>
         <ce-menu-item>
           70
         </ce-menu-item>
         <ce-menu-item>
           71
         </ce-menu-item>
         <ce-menu-item>
           72
         </ce-menu-item>
         <ce-menu-item>
           73
         </ce-menu-item>
         <ce-menu-item>
           74
         </ce-menu-item>
         <ce-menu-item>
           75
         </ce-menu-item>
         <ce-menu-item>
           76
         </ce-menu-item>
         <ce-menu-item>
           77
         </ce-menu-item>
         <ce-menu-item>
           78
         </ce-menu-item>
         <ce-menu-item>
           79
         </ce-menu-item>
         <ce-menu-item>
           80
         </ce-menu-item>
         <ce-menu-item>
           81
         </ce-menu-item>
         <ce-menu-item>
           82
         </ce-menu-item>
         <ce-menu-item>
           83
         </ce-menu-item>
         <ce-menu-item>
           84
         </ce-menu-item>
         <ce-menu-item>
           85
         </ce-menu-item>
         <ce-menu-item>
           86
         </ce-menu-item>
         <ce-menu-item>
           87
         </ce-menu-item>
         <ce-menu-item>
           88
         </ce-menu-item>
         <ce-menu-item>
           89
         </ce-menu-item>
         <ce-menu-item>
           90
         </ce-menu-item>
         <ce-menu-item>
           91
         </ce-menu-item>
         <ce-menu-item>
           92
         </ce-menu-item>
         <ce-menu-item>
           93
         </ce-menu-item>
         <ce-menu-item>
           94
         </ce-menu-item>
         <ce-menu-item>
           95
         </ce-menu-item>
         <ce-menu-item>
           96
         </ce-menu-item>
         <ce-menu-item>
           97
         </ce-menu-item>
         <ce-menu-item>
           98
         </ce-menu-item>
         <ce-menu-item>
           99
         </ce-menu-item>
         <ce-menu-item>
           100
         </ce-menu-item>
       </ce-menu>
     </ce-dropdown>
    </mock:shadow-root>
  </ce-quantity-select>
    `);
  });
});
