name: Components Tests

on:
  pull_request:
    types: [review_requested]
    paths:
      - "packages/components/src/**/*.tsx"
      - "packages/components/src/**/*.snap"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.16
        uses: actions/setup-node@v4
        with:
          node-version: 18.16
      - name: Enable Corepack
        run: corepack enable
      - name: Install dependencies (skip native builds)
        run: yarn install --immutable --mode=skip-build
      - name: Run component spec tests
        run: yarn workspace @surecart/components test --spec
        env:
          CI: true
          NODE_OPTIONS: "--max-old-space-size=4096"
