name: End-to-End Tests

on:
  pull_request:
    types: [ready_for_review, review_requested]

jobs:
    e2e-playwright:
        runs-on: ubuntu-22.04
        name: Playwright e2e tests
        strategy:
          matrix:
            browser: [chromium] #For now, skips - firefox, webkit
        steps:
            - uses: actions/checkout@v4
              with:
                  show-progress: ${{ runner.debug == '1' && 'true' || 'false' }}

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 16

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.1'

            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

            - name: Cache yarn dependencies
              uses: actions/cache@v4
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-

            - name: Composer Install
              run: composer install --optimize-autoloader --prefer-dist

            - name: Yarn Install
              run: yarn

            - name: Plugin Build scripts
              run: |
                  yarn bootstrap
                  yarn release:build
                  yarn wp-scripts build
                  yarn composer:release

            - name: Install WordPress and start the server
              run: |
                  yarn run wp-env start

                  # Activate a theme for rendering pages.
                  yarn run wp-env run tests-cli wp theme activate twentytwentyfour

                  # Set the permalink structure
                  yarn run wp-env run tests-cli wp rewrite structure /%postname%/
                  yarn run wp-env run tests-cli wp rewrite flush --hard

            - name: Install Playwright dependencies
              run: npx playwright install --with-deps ${{ matrix.browser }}

            - name: Run the playwright tests
              run: yarn run test:e2e --project=${{ matrix.browser }}

            - name: Stop the server
              run: yarn run wp-env stop
              if: always()
